"""add ranking to universities

Revision ID: 30c59b30f67b
Revises: b3a6028f8d3d
Create Date: 2026-05-30 12:50:45.559055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c59b30f67b'
down_revision: Union[str, None] = 'b3a6028f8d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('ranking', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'ranking')
    # ### end Alembic commands ###