"""add exam_type booleans to majors

Revision ID: 651de63c905b
Revises: a1b2c3d4e5f6
Create Date: 2026-05-30 14:58:58.326559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651de63c905b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majors', sa.Column('is_normal', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('majors', sa.Column('is_art', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('majors', sa.Column('is_sports', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('majors', 'is_sports')
    op.drop_column('majors', 'is_art')
    op.drop_column('majors', 'is_normal')
    # ### end Alembic commands ###