"""init: create all tables

Revision ID: b3a6028f8d3d
Revises: 
Create Date: 2026-05-28 22:53:19.517462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3a6028f8d3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('degree', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('courses', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('career_directions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('avg_salary', sa.Integer(), nullable=True),
    sa.Column('subject_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_majors_name'), 'majors', ['name'], unique=False)
    op.create_table('score_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cumulative_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_segments_province'), 'score_segments', ['province'], unique=False)
    op.create_index(op.f('ix_score_segments_year'), 'score_segments', ['year'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tuition_min', sa.Integer(), nullable=True),
    sa.Column('tuition_max', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_index(op.f('ix_universities_province'), 'universities', ['province'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('membership_tier', sa.String(length=20), nullable=False),
    sa.Column('membership_expires_at', sa.DateTime(), nullable=True),
    sa.Column('daily_chat_count', sa.Integer(), nullable=False),
    sa.Column('last_chat_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('admission_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=True),
    sa.Column('province', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=30), nullable=True),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('min_rank', sa.Integer(), nullable=True),
    sa.Column('avg_rank', sa.Integer(), nullable=True),
    sa.Column('plan_count', sa.Integer(), nullable=True),
    sa.Column('actual_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_records_province'), 'admission_records', ['province'], unique=False)
    op.create_index(op.f('ix_admission_records_university_id'), 'admission_records', ['university_id'], unique=False)
    op.create_index(op.f('ix_admission_records_year'), 'admission_records', ['year'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('university_majors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('ranking', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_majors_major_id'), 'university_majors', ['major_id'], unique=False)
    op.create_index(op.f('ix_university_majors_university_id'), 'university_majors', ['university_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('basic_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('values_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_university_majors_university_id'), table_name='university_majors')
    op.drop_index(op.f('ix_university_majors_major_id'), table_name='university_majors')
    op.drop_table('university_majors')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_admission_records_year'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_university_id'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_province'), table_name='admission_records')
    op.drop_table('admission_records')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_province'), table_name='universities')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_score_segments_year'), table_name='score_segments')
    op.drop_index(op.f('ix_score_segments_province'), table_name='score_segments')
    op.drop_table('score_segments')
    op.drop_index(op.f('ix_majors_name'), table_name='majors')
    op.drop_table('majors')
    # ### end Alembic commands ###