"""种子数据：常见本科专业"""
import asyncio
import uuid
import sys
sys.path.insert(0, "backend")

from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import async_session
from app.models.major import Major

MAJORS = [
    # ── 工学 ─────────────────────────────────────────────
    {"name": "计算机科学与技术", "category": "工学", "duration": 4,
     "courses": ["数据结构", "操作系统", "计算机网络", "数据库", "编译原理", "算法设计"],
     "career_directions": ["软件工程师", "算法工程师", "系统架构师", "数据工程师"],
     "avg_salary": 15000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "软件工程", "category": "工学", "duration": 4,
     "courses": ["程序设计", "数据结构", "软件工程导论", "软件测试", "项目管理"],
     "career_directions": ["软件开发", "项目经理", "产品经理", "测试工程师"],
     "avg_salary": 14000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "电子信息工程", "category": "工学", "duration": 4,
     "courses": ["电路分析", "信号与系统", "数字电路", "模拟电路", "通信原理"],
     "career_directions": ["硬件工程师", "通信工程师", "嵌入式开发", "IC设计"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "土木工程", "category": "工学", "duration": 4,
     "courses": ["结构力学", "材料力学", "土力学", "混凝土结构", "钢结构"],
     "career_directions": ["结构设计", "施工管理", "工程造价", "监理"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "人工智能", "category": "工学", "duration": 4,
     "courses": ["机器学习", "深度学习", "自然语言处理", "计算机视觉", "强化学习"],
     "career_directions": ["AI工程师", "算法研究员", "数据科学家"],
     "avg_salary": 18000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "机械工程", "category": "工学", "duration": 4,
     "courses": ["机械制图", "理论力学", "材料力学", "机械设计", "制造技术基础"],
     "career_directions": ["机械工程师", "自动化工程师", "工业设计", "质量管理"],
     "avg_salary": 9500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "自动化", "category": "工学", "duration": 4,
     "courses": ["电路原理", "自动控制原理", "电机与拖动", "过程控制", "PLC编程"],
     "career_directions": ["自动化工程师", "控制算法", "机器人开发", "工业自动化"],
     "avg_salary": 11000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "电气工程及其自动化", "category": "工学", "duration": 4,
     "courses": ["电路分析", "电机学", "电力系统分析", "高电压技术", "电力电子"],
     "career_directions": ["电力工程师", "电网运维", "新能源研发", "电气设备设计"],
     "avg_salary": 10500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "通信工程", "category": "工学", "duration": 4,
     "courses": ["通信原理", "数字信号处理", "电磁场与微波", "移动通信", "光纤通信"],
     "career_directions": ["通信工程师", "网络规划", "射频工程师", "5G研发"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "建筑学", "category": "工学", "duration": 5,
     "courses": ["建筑设计基础", "建筑历史", "建筑构造", "建筑物理", "城市规划原理"],
     "career_directions": ["建筑师", "城市规划师", "室内设计", "景观设计"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "材料科学与工程", "category": "工学", "duration": 4,
     "courses": ["材料科学基础", "材料力学性能", "材料物理", "材料化学", "材料分析测试"],
     "career_directions": ["材料工程师", "新能源材料研发", "半导体材料", "质量检测"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "环境工程", "category": "工学", "duration": 4,
     "courses": ["环境化学", "水污染控制", "大气污染控制", "环境监测", "环境影响评价"],
     "career_directions": ["环保工程师", "环评工程师", "环境监测", "水处理工程师"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "车辆工程", "category": "工学", "duration": 4,
     "courses": ["汽车构造", "汽车理论", "汽车设计", "汽车电子", "新能源汽车技术"],
     "career_directions": ["汽车设计", "新能源研发", "汽车电子", "智能驾驶"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "数据科学与大数据技术", "category": "工学", "duration": 4,
     "courses": ["概率统计", "数据挖掘", "大数据处理技术", "机器学习", "数据可视化"],
     "career_directions": ["数据分析师", "大数据工程师", "数据科学家", "BI工程师"],
     "avg_salary": 14000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "信息安全", "category": "工学", "duration": 4,
     "courses": ["密码学", "网络安全", "操作系统安全", "入侵检测", "信息对抗"],
     "career_directions": ["安全工程师", "渗透测试", "安全运维", "安全研究员"],
     "avg_salary": 15000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "食品科学与工程", "category": "工学", "duration": 4,
     "courses": ["食品化学", "食品微生物", "食品加工学", "食品营养学", "食品安全"],
     "career_directions": ["食品研发", "质量检测", "营养师", "食品监管"],
     "avg_salary": 7000,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 理学 ─────────────────────────────────────────────
    {"name": "数学与应用数学", "category": "理学", "duration": 4,
     "courses": ["数学分析", "高等代数", "概率论", "常微分方程", "数值分析"],
     "career_directions": ["数学教师", "金融分析师", "数据科学家", "精算师"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "物理学", "category": "理学", "duration": 4,
     "courses": ["力学", "热学", "电磁学", "量子力学", "统计物理"],
     "career_directions": ["物理教师", "科研院所", "半导体研发", "光电工程师"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "化学", "category": "理学", "duration": 4,
     "courses": ["无机化学", "有机化学", "物理化学", "分析化学", "结构化学"],
     "career_directions": ["化学教师", "化工研发", "药物研发", "材料研发"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["化学"]}},
    {"name": "生物科学", "category": "理学", "duration": 4,
     "courses": ["普通生物学", "生物化学", "分子生物学", "遗传学", "细胞生物学"],
     "career_directions": ["生物教师", "生物技术", "医药研发", "基因工程"],
     "avg_salary": 7500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "统计学", "category": "理学", "duration": 4,
     "courses": ["概率论", "数理统计", "回归分析", "时间序列", "多元统计分析"],
     "career_directions": ["统计分析师", "精算师", "数据分析师", "量化研究员"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "应用心理学", "category": "理学", "duration": 4,
     "courses": ["普通心理学", "实验心理学", "心理统计", "发展心理学", "心理咨询"],
     "career_directions": ["心理咨询师", "人力资源", "用户体验研究", "教育咨询"],
     "avg_salary": 8000,
     "subject_requirements": {}},

    # ── 医学 ─────────────────────────────────────────────
    {"name": "临床医学", "category": "医学", "duration": 5,
     "courses": ["人体解剖学", "生理学", "病理学", "药理学", "内科学", "外科学"],
     "career_directions": ["临床医生", "医学研究", "公共卫生"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理", "化学"]}},
    {"name": "口腔医学", "category": "医学", "duration": 5,
     "courses": ["口腔解剖生理学", "口腔组织病理学", "口腔内科学", "口腔颌面外科学", "口腔修复学"],
     "career_directions": ["口腔医生", "正畸医师", "口腔种植", "口腔美容"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理", "化学"]}},
    {"name": "药学", "category": "医学", "duration": 4,
     "courses": ["药物化学", "药理学", "药剂学", "药物分析", "临床药学"],
     "career_directions": ["药师", "药物研发", "药品监管", "医药代表"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "护理学", "category": "医学", "duration": 4,
     "courses": ["护理学基础", "内科护理学", "外科护理学", "妇产科护理学", "急救护理"],
     "career_directions": ["护士", "护理管理", "社区护理", "康复护理"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "中医学", "category": "医学", "duration": 5,
     "courses": ["中医基础理论", "中医诊断学", "中药学", "方剂学", "针灸学"],
     "career_directions": ["中医师", "针灸推拿", "中医养生", "中医科研"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 经济学 ───────────────────────────────────────────
    {"name": "金融学", "category": "经济学", "duration": 4,
     "courses": ["微观经济学", "宏观经济学", "金融学", "投资学", "金融工程"],
     "career_directions": ["银行", "证券", "基金", "保险", "金融科技"],
     "avg_salary": 12000,
     "subject_requirements": {}},
    {"name": "经济学", "category": "经济学", "duration": 4,
     "courses": ["政治经济学", "微观经济学", "宏观经济学", "计量经济学", "发展经济学"],
     "career_directions": ["经济分析师", "政策研究", "投资顾问", "公务员"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "国际经济与贸易", "category": "经济学", "duration": 4,
     "courses": ["国际贸易理论", "国际贸易实务", "国际结算", "外贸函电", "国际商法"],
     "career_directions": ["外贸业务员", "跨境电商", "报关员", "国际商务"],
     "avg_salary": 9000,
     "subject_requirements": {}},

    # ── 管理学 ───────────────────────────────────────────
    {"name": "会计学", "category": "管理学", "duration": 4,
     "courses": ["基础会计", "中级财务会计", "审计学", "成本管理", "税法"],
     "career_directions": ["会计师", "审计师", "财务分析", "税务师"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "工商管理", "category": "管理学", "duration": 4,
     "courses": ["管理学原理", "市场营销", "人力资源管理", "战略管理", "运营管理"],
     "career_directions": ["企业管理", "管理咨询", "产品经理", "创业者"],
     "avg_salary": 9500,
     "subject_requirements": {}},
    {"name": "市场营销", "category": "管理学", "duration": 4,
     "courses": ["市场营销学", "消费者行为学", "品牌管理", "数字营销", "市场调研"],
     "career_directions": ["市场经理", "品牌策划", "新媒体运营", "销售管理"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "人力资源管理", "category": "管理学", "duration": 4,
     "courses": ["人力资源管理", "组织行为学", "劳动法", "薪酬管理", "招聘与配置"],
     "career_directions": ["HR专员", "招聘经理", "培训师", "组织发展"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "物流管理", "category": "管理学", "duration": 4,
     "courses": ["物流学导论", "供应链管理", "仓储管理", "运输管理", "物流信息系统"],
     "career_directions": ["物流经理", "供应链管理", "仓储规划", "电商物流"],
     "avg_salary": 8000,
     "subject_requirements": {}},

    # ── 法学 ─────────────────────────────────────────────
    {"name": "法学", "category": "法学", "duration": 4,
     "courses": ["宪法", "民法", "刑法", "行政法", "国际法", "诉讼法"],
     "career_directions": ["律师", "法官", "检察官", "法务", "公务员"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "社会学", "category": "法学", "duration": 4,
     "courses": ["社会学概论", "社会调查方法", "社会心理学", "人口学", "社会统计学"],
     "career_directions": ["社会工作者", "政策研究", "市场调查", "NGO"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "政治学与行政学", "category": "法学", "duration": 4,
     "courses": ["政治学原理", "行政学原理", "公共政策", "比较政治", "国际关系"],
     "career_directions": ["公务员", "政策分析师", "国际组织", "媒体评论"],
     "avg_salary": 7500,
     "subject_requirements": {}},

    # ── 文学 ─────────────────────────────────────────────
    {"name": "英语", "category": "文学", "duration": 4,
     "courses": ["综合英语", "英语写作", "翻译理论与实践", "英美文学", "语言学"],
     "career_directions": ["翻译", "外贸", "教育", "国际组织"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "汉语言文学", "category": "文学", "duration": 4,
     "courses": ["现代汉语", "古代汉语", "中国古代文学", "中国现当代文学", "文学概论"],
     "career_directions": ["语文教师", "编辑", "文案策划", "公务员", "作家"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "新闻学", "category": "文学", "duration": 4,
     "courses": ["新闻学概论", "新闻采访与写作", "新闻编辑", "传播学", "媒介经营与管理"],
     "career_directions": ["记者", "编辑", "新媒体运营", "公关", "自媒体"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "广告学", "category": "文学", "duration": 4,
     "courses": ["广告学概论", "广告策划", "广告创意", "品牌传播", "数字广告"],
     "career_directions": ["广告策划", "品牌经理", "创意总监", "媒介购买"],
     "avg_salary": 8500,
     "subject_requirements": {}},

    # ── 教育学 ───────────────────────────────────────────
    {"name": "教育学", "category": "教育学", "duration": 4,
     "courses": ["教育学原理", "教育心理学", "教育研究方法", "课程与教学论", "教育史"],
     "career_directions": ["教师", "教育研究员", "培训师", "教育行政"],
     "avg_salary": 7500,
     "subject_requirements": {}},
    {"name": "学前教育", "category": "教育学", "duration": 4,
     "courses": ["学前教育学", "儿童发展心理学", "幼儿园课程设计", "幼儿游戏", "艺术教育"],
     "career_directions": ["幼儿教师", "早教机构", "儿童教育研究", "绘本编辑"],
     "avg_salary": 6000,
     "subject_requirements": {}},

    # ── 历史学 ───────────────────────────────────────────
    {"name": "历史学", "category": "历史学", "duration": 4,
     "courses": ["中国通史", "世界通史", "史学概论", "考古学概论", "历史地理学"],
     "career_directions": ["历史教师", "博物馆", "考古", "文史编辑", "公务员"],
     "avg_salary": 6500,
     "subject_requirements": {}},

    # ── 哲学 ─────────────────────────────────────────────
    {"name": "哲学", "category": "哲学", "duration": 4,
     "courses": ["哲学导论", "马克思主义哲学", "中国哲学史", "西方哲学史", "逻辑学"],
     "career_directions": ["教师", "出版编辑", "公务员", "企业文化", "咨询"],
     "avg_salary": 7000,
     "subject_requirements": {}},

    # ── 农学 ─────────────────────────────────────────────
    {"name": "农学", "category": "农学", "duration": 4,
     "courses": ["植物学", "作物栽培学", "作物育种学", "土壤学", "农业生态学"],
     "career_directions": ["农技推广", "种业研发", "农业管理", "农业科研"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "动物医学", "category": "农学", "duration": 5,
     "courses": ["动物解剖学", "动物生理学", "兽医微生物学", "兽医内科学", "兽医外科学"],
     "career_directions": ["兽医", "宠物医生", "动物检疫", "兽药研发"],
     "avg_salary": 7500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 艺术学 ───────────────────────────────────────────
    {"name": "视觉传达设计", "category": "艺术学", "duration": 4,
     "courses": ["设计素描", "色彩构成", "字体设计", "版式设计", "品牌形象设计"],
     "career_directions": ["平面设计师", "UI设计师", "品牌设计", "包装设计"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "环境设计", "category": "艺术学", "duration": 4,
     "courses": ["设计表现技法", "室内设计原理", "景观设计", "装饰材料", "人体工程学"],
     "career_directions": ["室内设计师", "景观设计师", "软装设计", "展览设计"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "数字媒体艺术", "category": "艺术学", "duration": 4,
     "courses": ["数字影像", "三维动画", "交互设计", "游戏设计", "数字音频"],
     "career_directions": ["游戏美术", "动画制作", "影视后期", "交互设计师"],
     "avg_salary": 9000,
     "subject_requirements": {}},

    # ── 工学（补充）─────────────────────────────────────────
    {"name": "航空航天工程", "category": "工学", "duration": 4,
     "courses": ["空气动力学", "飞行器结构设计", "飞行力学", "航空发动机原理", "复合材料"],
     "career_directions": ["航空设计师", "航天工程师", "飞行器制造", "科研人员"],
     "avg_salary": 13000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "核工程与核技术", "category": "工学", "duration": 4,
     "courses": ["核反应堆物理", "核辐射探测", "核电厂运行", "核安全分析", "热工水力学"],
     "career_directions": ["核电工程师", "核安全工程师", "辐射防护", "科研院所"],
     "avg_salary": 11000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "物联网工程", "category": "工学", "duration": 4,
     "courses": ["传感器原理", "嵌入式系统", "物联网通信", "云计算", "RFID技术"],
     "career_directions": ["物联网工程师", "嵌入式开发", "智慧城市", "智能家居"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "机器人工程", "category": "工学", "duration": 4,
     "courses": ["机器人学", "运动控制", "机器视觉", "人工智能", "ROS系统"],
     "career_directions": ["机器人工程师", "算法工程师", "自动化集成", "研发工程师"],
     "avg_salary": 13000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "新能源科学与工程", "category": "工学", "duration": 4,
     "courses": ["太阳能利用", "风力发电", "生物质能", "储能技术", "新能源系统"],
     "career_directions": ["新能源工程师", "光伏研发", "风电运维", "储能研发"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "光电信息科学与工程", "category": "工学", "duration": 4,
     "courses": ["物理光学", "应用光学", "光电子学", "激光原理", "光纤通信"],
     "career_directions": ["光电工程师", "光学设计", "激光技术", "显示技术"],
     "avg_salary": 10500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "测绘工程", "category": "工学", "duration": 4,
     "courses": ["测量学", "误差理论与测量平差", "大地测量", "GPS原理", "遥感技术"],
     "career_directions": ["测绘工程师", "GIS工程师", "遥感分析", "地理信息"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "纺织工程", "category": "工学", "duration": 4,
     "courses": ["纺织材料学", "纺纱学", "织造学", "织物结构设计", "纺织品贸易"],
     "career_directions": ["纺织工程师", "面料研发", "质量管理", "纺织品贸易"],
     "avg_salary": 7500,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "石油工程", "category": "工学", "duration": 4,
     "courses": ["油层物理", "渗流力学", "采油工程", "钻井工程", "油藏工程"],
     "career_directions": ["石油工程师", "钻井工程师", "油藏分析", "油田开发"],
     "avg_salary": 11000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "智能制造工程", "category": "工学", "duration": 4,
     "courses": ["智能制造系统", "工业物联网", "数字孪生", "工业机器人", "MES系统"],
     "career_directions": ["智能制造工程师", "工业互联网", "数字化工厂", "系统集成"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "集成电路设计与集成系统", "category": "工学", "duration": 4,
     "courses": ["数字集成电路设计", "模拟集成电路设计", "半导体器件", "EDA技术", "VLSI设计"],
     "career_directions": ["IC设计工程师", "芯片验证", "版图设计", "FPGA开发"],
     "avg_salary": 16000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "网络工程", "category": "工学", "duration": 4,
     "courses": ["计算机网络", "网络协议分析", "网络安全", "路由与交换", "云计算技术"],
     "career_directions": ["网络工程师", "运维工程师", "网络安全", "云架构师"],
     "avg_salary": 11500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "给排水科学与工程", "category": "工学", "duration": 4,
     "courses": ["水力学", "水分析化学", "给水工程", "排水工程", "建筑给排水"],
     "career_directions": ["给排水工程师", "水处理工程师", "市政设计", "环保工程"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "城乡规划", "category": "工学", "duration": 5,
     "courses": ["城市规划原理", "城市设计", "区域规划", "城市道路交通", "GIS应用"],
     "career_directions": ["规划师", "城市设计", "国土空间规划", "咨询顾问"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "安全工程", "category": "工学", "duration": 4,
     "courses": ["安全系统工程", "安全评价", "职业卫生", "消防安全", "应急管理"],
     "career_directions": ["安全工程师", "安全评价师", "应急管理", "职业健康"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},

    # ── 理学（补充）─────────────────────────────────────────
    {"name": "信息与计算科学", "category": "理学", "duration": 4,
     "courses": ["数值分析", "运筹学", "信息论", "算法设计", "数据结构"],
     "career_directions": ["算法工程师", "数据分析师", "软件开发", "科研人员"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "天文学", "category": "理学", "duration": 4,
     "courses": ["普通天文学", "天体物理学", "天体测量", "宇宙学", "天文观测"],
     "career_directions": ["天文研究员", "科普教育", "航天科技", "数据科学"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["物理"], "prefer": ["数学"]}},
    {"name": "地理科学", "category": "理学", "duration": 4,
     "courses": ["自然地理学", "人文地理学", "地图学", "GIS原理", "遥感概论"],
     "career_directions": ["地理教师", "GIS工程师", "城市规划", "环境监测"],
     "avg_salary": 7500,
     "subject_requirements": {"prefer": ["地理"]}},
    {"name": "大气科学", "category": "理学", "duration": 4,
     "courses": ["大气物理学", "天气学原理", "气候学", "数值天气预报", "卫星气象学"],
     "career_directions": ["气象预报员", "气候分析师", "航空气象", "环保监测"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "海洋科学", "category": "理学", "duration": 4,
     "courses": ["海洋学", "海洋化学", "海洋生物学", "物理海洋学", "海洋地质"],
     "career_directions": ["海洋研究员", "海洋环保", "海洋资源开发", "科研人员"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "生态学", "category": "理学", "duration": 4,
     "courses": ["生态学基础", "种群生态学", "生态系统生态学", "生态工程", "保护生物学"],
     "career_directions": ["生态研究员", "环保工程师", "自然保护区", "生态修复"],
     "avg_salary": 7500,
     "subject_requirements": {"prefer": ["生物"]}},

    # ── 医学（补充）─────────────────────────────────────────
    {"name": "基础医学", "category": "医学", "duration": 5,
     "courses": ["人体解剖学", "组织胚胎学", "生理学", "病理学", "药理学"],
     "career_directions": ["医学研究员", "高校教师", "病理医师", "药物研发"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "预防医学", "category": "医学", "duration": 5,
     "courses": ["流行病学", "卫生统计学", "环境卫生学", "营养与食品卫生", "职业卫生"],
     "career_directions": ["疾控医师", "公卫医师", "卫生监督", "健康管理"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "医学影像学", "category": "医学", "duration": 5,
     "courses": ["影像诊断学", "超声诊断学", "介入放射学", "CT诊断", "MRI诊断"],
     "career_directions": ["影像科医师", "超声医师", "介入医师", "放射科"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["化学"], "prefer": ["物理", "生物"]}},
    {"name": "麻醉学", "category": "医学", "duration": 5,
     "courses": ["麻醉解剖学", "麻醉生理学", "临床麻醉学", "危重病学", "疼痛诊疗"],
     "career_directions": ["麻醉医师", "疼痛科医师", "ICU医师", "急救医学"],
     "avg_salary": 14000,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "康复治疗学", "category": "医学", "duration": 4,
     "courses": ["康复评定学", "运动疗法", "作业疗法", "物理因子治疗", "康复工程"],
     "career_directions": ["康复治疗师", "康复医师", "运动康复", "社区康复"],
     "avg_salary": 7500,
     "subject_requirements": {"prefer": ["生物"]}},
    {"name": "中西医临床医学", "category": "医学", "duration": 5,
     "courses": ["中医基础理论", "西医诊断学", "中药学", "方剂学", "中西医结合内科学"],
     "career_directions": ["中西医结合医师", "全科医师", "中医科", "基层医疗"],
     "avg_salary": 9500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 经济学（补充）───────────────────────────────────────
    {"name": "财政学", "category": "经济学", "duration": 4,
     "courses": ["财政学原理", "税收学", "公共经济学", "政府预算", "国际税收"],
     "career_directions": ["税务公务员", "财税顾问", "会计师", "财务分析"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "保险学", "category": "经济学", "duration": 4,
     "courses": ["保险学原理", "财产保险", "人身保险", "精算学", "风险管理"],
     "career_directions": ["保险精算师", "核保理赔", "风险管理", "保险代理人"],
     "avg_salary": 10000,
     "subject_requirements": {"prefer": ["数学"]}},
    {"name": "投资学", "category": "经济学", "duration": 4,
     "courses": ["证券投资学", "项目投资", "金融衍生品", "风险投资", "资产定价"],
     "career_directions": ["投资分析师", "基金经理", "证券分析师", "投资顾问"],
     "avg_salary": 13000,
     "subject_requirements": {"prefer": ["数学"]}},
    {"name": "税收学", "category": "经济学", "duration": 4,
     "courses": ["中国税制", "国际税收", "税务管理", "税务筹划", "税务会计"],
     "career_directions": ["税务师", "税务公务员", "财税顾问", "审计师"],
     "avg_salary": 9500,
     "subject_requirements": {}},
    {"name": "信用管理", "category": "经济学", "duration": 4,
     "courses": ["信用管理学", "征信技术", "信用评级", "风险管理", "消费者信用"],
     "career_directions": ["信用分析师", "风控专员", "征信机构", "银行信贷"],
     "avg_salary": 9000,
     "subject_requirements": {}},

    # ── 管理学（补充）───────────────────────────────────────
    {"name": "财务管理", "category": "管理学", "duration": 4,
     "courses": ["财务管理学", "财务分析", "成本管理", "税务筹划", "审计学"],
     "career_directions": ["财务经理", "会计师", "审计师", "投资分析"],
     "avg_salary": 9500,
     "subject_requirements": {}},
    {"name": "审计学", "category": "管理学", "duration": 4,
     "courses": ["审计学原理", "财务审计", "内部审计", "信息系统审计", "审计准则"],
     "career_directions": ["审计师", "注册会计师", "内部审计", "风险控制"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "信息管理与信息系统", "category": "管理学", "duration": 4,
     "courses": ["管理信息系统", "数据库技术", "信息系统开发", "IT项目管理", "数据分析"],
     "career_directions": ["IT项目经理", "系统分析师", "数据管理", "企业信息化"],
     "avg_salary": 11000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "工程管理", "category": "管理学", "duration": 4,
     "courses": ["工程项目管理", "工程经济学", "工程造价", "施工组织", "合同管理"],
     "career_directions": ["项目经理", "造价工程师", "工程咨询", "房地产开发"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "公共事业管理", "category": "管理学", "duration": 4,
     "courses": ["公共管理学", "公共政策", "非营利组织管理", "公共经济学", "社会调查"],
     "career_directions": ["公务员", "事业单位", "NGO管理", "社区工作者"],
     "avg_salary": 6500,
     "subject_requirements": {}},
    {"name": "行政管理", "category": "管理学", "duration": 4,
     "courses": ["行政管理学", "政治学原理", "公共政策", "行政法", "公文写作"],
     "career_directions": ["公务员", "行政助理", "办公室管理", "人力资源"],
     "avg_salary": 6500,
     "subject_requirements": {}},
    {"name": "旅游管理", "category": "管理学", "duration": 4,
     "courses": ["旅游学概论", "旅游经济学", "酒店管理", "旅行社管理", "旅游规划"],
     "career_directions": ["旅游规划师", "酒店经理", "导游", "文旅项目"],
     "avg_salary": 6000,
     "subject_requirements": {}},
    {"name": "电子商务", "category": "管理学", "duration": 4,
     "courses": ["电子商务概论", "网络营销", "供应链管理", "电子支付", "数据分析"],
     "career_directions": ["电商运营", "产品经理", "网络营销", "数据运营"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "文化产业管理", "category": "管理学", "duration": 4,
     "courses": ["文化产业概论", "文化市场营销", "文化项目管理", "文化政策", "版权管理"],
     "career_directions": ["文化项目策划", "文化经纪人", "博物馆管理", "影视制作"],
     "avg_salary": 7000,
     "subject_requirements": {}},

    # ── 法学（补充）─────────────────────────────────────────
    {"name": "知识产权", "category": "法学", "duration": 4,
     "courses": ["知识产权法", "专利法", "商标法", "著作权法", "知识产权管理"],
     "career_directions": ["知识产权律师", "专利代理人", "商标代理", "法务专员"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "社会工作", "category": "法学", "duration": 4,
     "courses": ["社会工作概论", "个案工作", "小组工作", "社区工作", "社会政策"],
     "career_directions": ["社工师", "社区工作者", "公益组织", "民政系统"],
     "avg_salary": 5500,
     "subject_requirements": {}},
    {"name": "马克思主义理论", "category": "法学", "duration": 4,
     "courses": ["马克思主义基本原理", "中国化马克思主义", "思想政治教育", "政治学原理"],
     "career_directions": ["高校辅导员", "思政教师", "公务员", "党建工作者"],
     "avg_salary": 6000,
     "subject_requirements": {"prefer": ["政治"]}},

    # ── 文学（补充）─────────────────────────────────────────
    {"name": "日语", "category": "文学", "duration": 4,
     "courses": ["基础日语", "高级日语", "日语翻译", "日本概况", "商务日语"],
     "career_directions": ["翻译", "日语教师", "外贸专员", "日企职员"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "翻译", "category": "文学", "duration": 4,
     "courses": ["翻译理论", "口译", "笔译", "同声传译", "计算机辅助翻译"],
     "career_directions": ["口译员", "笔译员", "同声传译", "本地化工程师"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "商务英语", "category": "文学", "duration": 4,
     "courses": ["商务英语", "国际贸易实务", "商务谈判", "跨文化交际", "外贸函电"],
     "career_directions": ["外贸业务员", "商务翻译", "国际商务", "外企职员"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "传播学", "category": "文学", "duration": 4,
     "courses": ["传播学概论", "媒介研究", "舆论学", "网络传播", "传播研究方法"],
     "career_directions": ["媒体策划", "公关专员", "新媒体运营", "市场调研"],
     "avg_salary": 7500,
     "subject_requirements": {}},
    {"name": "编辑出版学", "category": "文学", "duration": 4,
     "courses": ["编辑学概论", "出版学基础", "数字出版", "校对实务", "出版营销"],
     "career_directions": ["图书编辑", "数字出版", "期刊编辑", "版权经理"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "法语", "category": "文学", "duration": 4,
     "courses": ["基础法语", "高级法语", "法语翻译", "法国文学", "法语口译"],
     "career_directions": ["翻译", "法语教师", "外交人员", "外贸专员"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "德语", "category": "文学", "duration": 4,
     "courses": ["基础德语", "高级德语", "德语翻译", "德国文学", "商务德语"],
     "career_directions": ["翻译", "德语教师", "德企职员", "外贸专员"],
     "avg_salary": 9000,
     "subject_requirements": {}},

    # ── 教育学（补充）───────────────────────────────────────
    {"name": "小学教育", "category": "教育学", "duration": 4,
     "courses": ["教育心理学", "小学语文教学", "小学数学教学", "班级管理", "儿童发展"],
     "career_directions": ["小学教师", "教育机构", "课程开发", "教育研究"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "体育教育", "category": "教育学", "duration": 4,
     "courses": ["运动解剖学", "运动生理学", "学校体育学", "体育教学论", "田径"],
     "career_directions": ["体育教师", "教练员", "健身教练", "体育管理"],
     "avg_salary": 6500,
     "subject_requirements": {},
     "is_sports": True},
    {"name": "特殊教育", "category": "教育学", "duration": 4,
     "courses": ["特殊教育学", "听力障碍教育", "智力障碍教育", "自闭症教育", "手语"],
     "career_directions": ["特教教师", "康复训练师", "残联系统", "公益组织"],
     "avg_salary": 6000,
     "subject_requirements": {}},
    {"name": "教育技术学", "category": "教育学", "duration": 4,
     "courses": ["教育技术学导论", "教学设计", "多媒体技术", "网络教育", "教育游戏"],
     "career_directions": ["教育产品经理", "课件开发", "在线教育", "培训讲师"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},

    # ── 历史学（补充）───────────────────────────────────────
    {"name": "世界史", "category": "历史学", "duration": 4,
     "courses": ["世界古代史", "世界中世纪史", "世界近现代史", "国际关系史", "史学理论"],
     "career_directions": ["历史教师", "研究员", "文博系统", "出版社"],
     "avg_salary": 6000,
     "subject_requirements": {"prefer": ["历史"]}},
    {"name": "考古学", "category": "历史学", "duration": 4,
     "courses": ["考古学通论", "田野考古", "中国考古学", "文物学", "博物馆学"],
     "career_directions": ["考古研究员", "博物馆", "文物保护", "文化遗产"],
     "avg_salary": 6500,
     "subject_requirements": {"prefer": ["历史"]}},
    {"name": "文物与博物馆学", "category": "历史学", "duration": 4,
     "courses": ["文物学概论", "博物馆学", "文物保护技术", "考古学基础", "文化遗产"],
     "career_directions": ["博物馆讲解", "文物保护", "考古助理", "文化管理"],
     "avg_salary": 6000,
     "subject_requirements": {"prefer": ["历史"]}},

    # ── 农学（补充）─────────────────────────────────────────
    {"name": "园艺", "category": "农学", "duration": 4,
     "courses": ["植物学", "园艺植物育种", "园艺栽培学", "设施园艺", "园艺产品贮藏"],
     "career_directions": ["园艺师", "农业技术员", "种业研发", "园林设计"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "植物保护", "category": "农学", "duration": 4,
     "courses": ["普通昆虫学", "植物病理学", "农业昆虫学", "农药学", "生物防治"],
     "career_directions": ["植保技术员", "农药研发", "植物检疫", "农业推广"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "林学", "category": "农学", "duration": 4,
     "courses": ["森林生态学", "林木育种", "森林培育", "森林保护", "森林经理学"],
     "career_directions": ["林业技术员", "林业公务员", "自然保护区", "碳汇研究"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "动物科学", "category": "农学", "duration": 4,
     "courses": ["动物生理学", "动物营养学", "饲料学", "动物遗传育种", "畜牧学"],
     "career_directions": ["畜牧技术员", "饲料研发", "种业公司", "动物营养"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "水产养殖学", "category": "农学", "duration": 4,
     "courses": ["水产养殖学", "鱼类学", "水产动物营养", "水产动物疾病", "水环境"],
     "career_directions": ["水产技术员", "水产养殖", "水产加工", "水产研究"],
     "avg_salary": 6000,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 艺术学（补充）───────────────────────────────────────
    {"name": "音乐学", "category": "艺术学", "duration": 4,
     "courses": ["音乐理论基础", "和声学", "音乐史", "作曲", "声乐/器乐"],
     "career_directions": ["音乐教师", "演奏家", "音乐制作", "艺术管理"],
     "avg_salary": 6500,
     "subject_requirements": {}},
    {"name": "美术学", "category": "艺术学", "duration": 4,
     "courses": ["素描", "色彩", "油画", "国画", "美术史"],
     "career_directions": ["美术教师", "画家", "插画师", "艺术策展"],
     "avg_salary": 6000,
     "subject_requirements": {}},
    {"name": "动画", "category": "艺术学", "duration": 4,
     "courses": ["动画原理", "角色设计", "场景设计", "三维动画", "动画制作"],
     "career_directions": ["动画师", "原画师", "游戏美术", "影视动画"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "广播电视编导", "category": "艺术学", "duration": 4,
     "courses": ["电视节目策划", "电视摄像", "非线性编辑", "电视导播", "纪录片创作"],
     "career_directions": ["编导", "摄像师", "后期制作", "自媒体"],
     "avg_salary": 7500,
     "subject_requirements": {}},
    {"name": "产品设计", "category": "艺术学", "duration": 4,
     "courses": ["工业设计史", "产品设计方法", "人机工程学", "材料与工艺", "产品造型"],
     "career_directions": ["产品设计师", "交互设计", "家具设计", "文创产品"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "表演", "category": "艺术学", "duration": 4,
     "courses": ["表演基础", "台词", "形体训练", "声乐", "剧目排练"],
     "career_directions": ["演员", "话剧演员", "影视表演", "模特"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "播音与主持艺术", "category": "艺术学", "duration": 4,
     "courses": ["普通话语音", "播音发声", "播音创作基础", "节目主持", "新闻播音"],
     "career_directions": ["主持人", "播音员", "记者", "自媒体主播"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "舞蹈学", "category": "艺术学", "duration": 4,
     "courses": ["舞蹈基础训练", "中国古典舞", "民族民间舞", "舞蹈编导", "舞蹈史"],
     "career_directions": ["舞蹈演员", "舞蹈教师", "编舞", "文艺团体"],
     "avg_salary": 6000,
     "subject_requirements": {}},
    {"name": "戏剧影视文学", "category": "艺术学", "duration": 4,
     "courses": ["戏剧概论", "电影史", "编剧基础", "影视评论", "剧本创作"],
     "career_directions": ["编剧", "剧评人", "影视策划", "文学编辑"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "书法学", "category": "艺术学", "duration": 4,
     "courses": ["楷书", "行书", "草书", "篆刻", "书法史"],
     "career_directions": ["书法家", "书法教师", "篆刻家", "文化传播"],
     "avg_salary": 5500,
     "subject_requirements": {}},

    # ── 体育类（教育学下，体育方向）───────────────────────────
    {"name": "运动训练", "category": "教育学", "duration": 4,
     "courses": ["运动训练学", "运动生理学", "运动心理学", "体育竞赛", "专项训练"],
     "career_directions": ["教练员", "体育教师", "运动康复", "体育管理"],
     "avg_salary": 6500,
     "subject_requirements": {},
     "is_normal": False, "is_sports": True},
    {"name": "武术与民族传统体育", "category": "教育学", "duration": 4,
     "courses": ["武术套路", "散打", "太极拳", "民族传统体育", "武术理论"],
     "career_directions": ["武术教练", "体育教师", "安保", "影视武指"],
     "avg_salary": 6000,
     "subject_requirements": {},
     "is_normal": False, "is_sports": True},
]


async def seed():
    async with async_session() as session:
        # 先清理关联的录取记录，再删除专业
        from app.models.admission import AdmissionRecord
        result = await session.execute(delete(AdmissionRecord))
        print(f"Deleted {result.rowcount} admission records")
        result = await session.execute(delete(Major))
        print(f"Deleted {result.rowcount} existing majors")

        for data in MAJORS:
            # 艺术学专业默认标记为艺术类（除非数据中已显式设置）
            if data.get("category") == "艺术学" and "is_art" not in data:
                data["is_art"] = True
                data.setdefault("is_normal", False)
            major = Major(id=uuid.uuid4(), **data)
            session.add(major)
        await session.commit()
        print(f"Inserted {len(MAJORS)} majors")


if __name__ == "__main__":
    asyncio.run(seed())