"""种子数据：常见本科专业"""
import asyncio
import uuid
import sys
sys.path.insert(0, "backend")

from sqlalchemy.ext.asyncio import AsyncSession
from app.database import async_session
from app.models.major import Major

MAJORS = [
    # ── 工学 ─────────────────────────────────────────────
    {"name": "计算机科学与技术", "category": "工学", "duration": 4,
     "courses": ["数据结构", "操作系统", "计算机网络", "数据库", "编译原理", "算法设计"],
     "career_directions": ["软件工程师", "算法工程师", "系统架构师", "数据工程师"],
     "avg_salary": 15000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "软件工程", "category": "工学", "duration": 4,
     "courses": ["程序设计", "数据结构", "软件工程导论", "软件测试", "项目管理"],
     "career_directions": ["软件开发", "项目经理", "产品经理", "测试工程师"],
     "avg_salary": 14000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "电子信息工程", "category": "工学", "duration": 4,
     "courses": ["电路分析", "信号与系统", "数字电路", "模拟电路", "通信原理"],
     "career_directions": ["硬件工程师", "通信工程师", "嵌入式开发", "IC设计"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "土木工程", "category": "工学", "duration": 4,
     "courses": ["结构力学", "材料力学", "土力学", "混凝土结构", "钢结构"],
     "career_directions": ["结构设计", "施工管理", "工程造价", "监理"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "人工智能", "category": "工学", "duration": 4,
     "courses": ["机器学习", "深度学习", "自然语言处理", "计算机视觉", "强化学习"],
     "career_directions": ["AI工程师", "算法研究员", "数据科学家"],
     "avg_salary": 18000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "机械工程", "category": "工学", "duration": 4,
     "courses": ["机械制图", "理论力学", "材料力学", "机械设计", "制造技术基础"],
     "career_directions": ["机械工程师", "自动化工程师", "工业设计", "质量管理"],
     "avg_salary": 9500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "自动化", "category": "工学", "duration": 4,
     "courses": ["电路原理", "自动控制原理", "电机与拖动", "过程控制", "PLC编程"],
     "career_directions": ["自动化工程师", "控制算法", "机器人开发", "工业自动化"],
     "avg_salary": 11000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "电气工程及其自动化", "category": "工学", "duration": 4,
     "courses": ["电路分析", "电机学", "电力系统分析", "高电压技术", "电力电子"],
     "career_directions": ["电力工程师", "电网运维", "新能源研发", "电气设备设计"],
     "avg_salary": 10500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "通信工程", "category": "工学", "duration": 4,
     "courses": ["通信原理", "数字信号处理", "电磁场与微波", "移动通信", "光纤通信"],
     "career_directions": ["通信工程师", "网络规划", "射频工程师", "5G研发"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "建筑学", "category": "工学", "duration": 5,
     "courses": ["建筑设计基础", "建筑历史", "建筑构造", "建筑物理", "城市规划原理"],
     "career_directions": ["建筑师", "城市规划师", "室内设计", "景观设计"],
     "avg_salary": 9000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "材料科学与工程", "category": "工学", "duration": 4,
     "courses": ["材料科学基础", "材料力学性能", "材料物理", "材料化学", "材料分析测试"],
     "career_directions": ["材料工程师", "新能源材料研发", "半导体材料", "质量检测"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "环境工程", "category": "工学", "duration": 4,
     "courses": ["环境化学", "水污染控制", "大气污染控制", "环境监测", "环境影响评价"],
     "career_directions": ["环保工程师", "环评工程师", "环境监测", "水处理工程师"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["物理"], "prefer": ["化学"]}},
    {"name": "车辆工程", "category": "工学", "duration": 4,
     "courses": ["汽车构造", "汽车理论", "汽车设计", "汽车电子", "新能源汽车技术"],
     "career_directions": ["汽车设计", "新能源研发", "汽车电子", "智能驾驶"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "数据科学与大数据技术", "category": "工学", "duration": 4,
     "courses": ["概率统计", "数据挖掘", "大数据处理技术", "机器学习", "数据可视化"],
     "career_directions": ["数据分析师", "大数据工程师", "数据科学家", "BI工程师"],
     "avg_salary": 14000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "信息安全", "category": "工学", "duration": 4,
     "courses": ["密码学", "网络安全", "操作系统安全", "入侵检测", "信息对抗"],
     "career_directions": ["安全工程师", "渗透测试", "安全运维", "安全研究员"],
     "avg_salary": 15000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "食品科学与工程", "category": "工学", "duration": 4,
     "courses": ["食品化学", "食品微生物", "食品加工学", "食品营养学", "食品安全"],
     "career_directions": ["食品研发", "质量检测", "营养师", "食品监管"],
     "avg_salary": 7000,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 理学 ─────────────────────────────────────────────
    {"name": "数学与应用数学", "category": "理学", "duration": 4,
     "courses": ["数学分析", "高等代数", "概率论", "常微分方程", "数值分析"],
     "career_directions": ["数学教师", "金融分析师", "数据科学家", "精算师"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "物理学", "category": "理学", "duration": 4,
     "courses": ["力学", "热学", "电磁学", "量子力学", "统计物理"],
     "career_directions": ["物理教师", "科研院所", "半导体研发", "光电工程师"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "化学", "category": "理学", "duration": 4,
     "courses": ["无机化学", "有机化学", "物理化学", "分析化学", "结构化学"],
     "career_directions": ["化学教师", "化工研发", "药物研发", "材料研发"],
     "avg_salary": 8000,
     "subject_requirements": {"must": ["化学"]}},
    {"name": "生物科学", "category": "理学", "duration": 4,
     "courses": ["普通生物学", "生物化学", "分子生物学", "遗传学", "细胞生物学"],
     "career_directions": ["生物教师", "生物技术", "医药研发", "基因工程"],
     "avg_salary": 7500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "统计学", "category": "理学", "duration": 4,
     "courses": ["概率论", "数理统计", "回归分析", "时间序列", "多元统计分析"],
     "career_directions": ["统计分析师", "精算师", "数据分析师", "量化研究员"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理"]}},
    {"name": "应用心理学", "category": "理学", "duration": 4,
     "courses": ["普通心理学", "实验心理学", "心理统计", "发展心理学", "心理咨询"],
     "career_directions": ["心理咨询师", "人力资源", "用户体验研究", "教育咨询"],
     "avg_salary": 8000,
     "subject_requirements": {}},

    # ── 医学 ─────────────────────────────────────────────
    {"name": "临床医学", "category": "医学", "duration": 5,
     "courses": ["人体解剖学", "生理学", "病理学", "药理学", "内科学", "外科学"],
     "career_directions": ["临床医生", "医学研究", "公共卫生"],
     "avg_salary": 10000,
     "subject_requirements": {"must": ["物理", "化学"]}},
    {"name": "口腔医学", "category": "医学", "duration": 5,
     "courses": ["口腔解剖生理学", "口腔组织病理学", "口腔内科学", "口腔颌面外科学", "口腔修复学"],
     "career_directions": ["口腔医生", "正畸医师", "口腔种植", "口腔美容"],
     "avg_salary": 12000,
     "subject_requirements": {"must": ["物理", "化学"]}},
    {"name": "药学", "category": "医学", "duration": 4,
     "courses": ["药物化学", "药理学", "药剂学", "药物分析", "临床药学"],
     "career_directions": ["药师", "药物研发", "药品监管", "医药代表"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "护理学", "category": "医学", "duration": 4,
     "courses": ["护理学基础", "内科护理学", "外科护理学", "妇产科护理学", "急救护理"],
     "career_directions": ["护士", "护理管理", "社区护理", "康复护理"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "中医学", "category": "医学", "duration": 5,
     "courses": ["中医基础理论", "中医诊断学", "中药学", "方剂学", "针灸学"],
     "career_directions": ["中医师", "针灸推拿", "中医养生", "中医科研"],
     "avg_salary": 8500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 经济学 ───────────────────────────────────────────
    {"name": "金融学", "category": "经济学", "duration": 4,
     "courses": ["微观经济学", "宏观经济学", "金融学", "投资学", "金融工程"],
     "career_directions": ["银行", "证券", "基金", "保险", "金融科技"],
     "avg_salary": 12000,
     "subject_requirements": {}},
    {"name": "经济学", "category": "经济学", "duration": 4,
     "courses": ["政治经济学", "微观经济学", "宏观经济学", "计量经济学", "发展经济学"],
     "career_directions": ["经济分析师", "政策研究", "投资顾问", "公务员"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "国际经济与贸易", "category": "经济学", "duration": 4,
     "courses": ["国际贸易理论", "国际贸易实务", "国际结算", "外贸函电", "国际商法"],
     "career_directions": ["外贸业务员", "跨境电商", "报关员", "国际商务"],
     "avg_salary": 9000,
     "subject_requirements": {}},

    # ── 管理学 ───────────────────────────────────────────
    {"name": "会计学", "category": "管理学", "duration": 4,
     "courses": ["基础会计", "中级财务会计", "审计学", "成本管理", "税法"],
     "career_directions": ["会计师", "审计师", "财务分析", "税务师"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "工商管理", "category": "管理学", "duration": 4,
     "courses": ["管理学原理", "市场营销", "人力资源管理", "战略管理", "运营管理"],
     "career_directions": ["企业管理", "管理咨询", "产品经理", "创业者"],
     "avg_salary": 9500,
     "subject_requirements": {}},
    {"name": "市场营销", "category": "管理学", "duration": 4,
     "courses": ["市场营销学", "消费者行为学", "品牌管理", "数字营销", "市场调研"],
     "career_directions": ["市场经理", "品牌策划", "新媒体运营", "销售管理"],
     "avg_salary": 9000,
     "subject_requirements": {}},
    {"name": "人力资源管理", "category": "管理学", "duration": 4,
     "courses": ["人力资源管理", "组织行为学", "劳动法", "薪酬管理", "招聘与配置"],
     "career_directions": ["HR专员", "招聘经理", "培训师", "组织发展"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "物流管理", "category": "管理学", "duration": 4,
     "courses": ["物流学导论", "供应链管理", "仓储管理", "运输管理", "物流信息系统"],
     "career_directions": ["物流经理", "供应链管理", "仓储规划", "电商物流"],
     "avg_salary": 8000,
     "subject_requirements": {}},

    # ── 法学 ─────────────────────────────────────────────
    {"name": "法学", "category": "法学", "duration": 4,
     "courses": ["宪法", "民法", "刑法", "行政法", "国际法", "诉讼法"],
     "career_directions": ["律师", "法官", "检察官", "法务", "公务员"],
     "avg_salary": 10000,
     "subject_requirements": {}},
    {"name": "社会学", "category": "法学", "duration": 4,
     "courses": ["社会学概论", "社会调查方法", "社会心理学", "人口学", "社会统计学"],
     "career_directions": ["社会工作者", "政策研究", "市场调查", "NGO"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "政治学与行政学", "category": "法学", "duration": 4,
     "courses": ["政治学原理", "行政学原理", "公共政策", "比较政治", "国际关系"],
     "career_directions": ["公务员", "政策分析师", "国际组织", "媒体评论"],
     "avg_salary": 7500,
     "subject_requirements": {}},

    # ── 文学 ─────────────────────────────────────────────
    {"name": "英语", "category": "文学", "duration": 4,
     "courses": ["综合英语", "英语写作", "翻译理论与实践", "英美文学", "语言学"],
     "career_directions": ["翻译", "外贸", "教育", "国际组织"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "汉语言文学", "category": "文学", "duration": 4,
     "courses": ["现代汉语", "古代汉语", "中国古代文学", "中国现当代文学", "文学概论"],
     "career_directions": ["语文教师", "编辑", "文案策划", "公务员", "作家"],
     "avg_salary": 7000,
     "subject_requirements": {}},
    {"name": "新闻学", "category": "文学", "duration": 4,
     "courses": ["新闻学概论", "新闻采访与写作", "新闻编辑", "传播学", "媒介经营与管理"],
     "career_directions": ["记者", "编辑", "新媒体运营", "公关", "自媒体"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "广告学", "category": "文学", "duration": 4,
     "courses": ["广告学概论", "广告策划", "广告创意", "品牌传播", "数字广告"],
     "career_directions": ["广告策划", "品牌经理", "创意总监", "媒介购买"],
     "avg_salary": 8500,
     "subject_requirements": {}},

    # ── 教育学 ───────────────────────────────────────────
    {"name": "教育学", "category": "教育学", "duration": 4,
     "courses": ["教育学原理", "教育心理学", "教育研究方法", "课程与教学论", "教育史"],
     "career_directions": ["教师", "教育研究员", "培训师", "教育行政"],
     "avg_salary": 7500,
     "subject_requirements": {}},
    {"name": "学前教育", "category": "教育学", "duration": 4,
     "courses": ["学前教育学", "儿童发展心理学", "幼儿园课程设计", "幼儿游戏", "艺术教育"],
     "career_directions": ["幼儿教师", "早教机构", "儿童教育研究", "绘本编辑"],
     "avg_salary": 6000,
     "subject_requirements": {}},

    # ── 历史学 ───────────────────────────────────────────
    {"name": "历史学", "category": "历史学", "duration": 4,
     "courses": ["中国通史", "世界通史", "史学概论", "考古学概论", "历史地理学"],
     "career_directions": ["历史教师", "博物馆", "考古", "文史编辑", "公务员"],
     "avg_salary": 6500,
     "subject_requirements": {}},

    # ── 哲学 ─────────────────────────────────────────────
    {"name": "哲学", "category": "哲学", "duration": 4,
     "courses": ["哲学导论", "马克思主义哲学", "中国哲学史", "西方哲学史", "逻辑学"],
     "career_directions": ["教师", "出版编辑", "公务员", "企业文化", "咨询"],
     "avg_salary": 7000,
     "subject_requirements": {}},

    # ── 农学 ─────────────────────────────────────────────
    {"name": "农学", "category": "农学", "duration": 4,
     "courses": ["植物学", "作物栽培学", "作物育种学", "土壤学", "农业生态学"],
     "career_directions": ["农技推广", "种业研发", "农业管理", "农业科研"],
     "avg_salary": 6500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},
    {"name": "动物医学", "category": "农学", "duration": 5,
     "courses": ["动物解剖学", "动物生理学", "兽医微生物学", "兽医内科学", "兽医外科学"],
     "career_directions": ["兽医", "宠物医生", "动物检疫", "兽药研发"],
     "avg_salary": 7500,
     "subject_requirements": {"must": ["化学"], "prefer": ["生物"]}},

    # ── 艺术学 ───────────────────────────────────────────
    {"name": "视觉传达设计", "category": "艺术学", "duration": 4,
     "courses": ["设计素描", "色彩构成", "字体设计", "版式设计", "品牌形象设计"],
     "career_directions": ["平面设计师", "UI设计师", "品牌设计", "包装设计"],
     "avg_salary": 8500,
     "subject_requirements": {}},
    {"name": "环境设计", "category": "艺术学", "duration": 4,
     "courses": ["设计表现技法", "室内设计原理", "景观设计", "装饰材料", "人体工程学"],
     "career_directions": ["室内设计师", "景观设计师", "软装设计", "展览设计"],
     "avg_salary": 8000,
     "subject_requirements": {}},
    {"name": "数字媒体艺术", "category": "艺术学", "duration": 4,
     "courses": ["数字影像", "三维动画", "交互设计", "游戏设计", "数字音频"],
     "career_directions": ["游戏美术", "动画制作", "影视后期", "交互设计师"],
     "avg_salary": 9000,
     "subject_requirements": {}},
]


async def seed():
    async with async_session() as session:
        for data in MAJORS:
            major = Major(id=uuid.uuid4(), **data)
            session.add(major)
        await session.commit()
        print(f"Inserted {len(MAJORS)} majors")


if __name__ == "__main__":
    asyncio.run(seed())