"""种子数据：985/211/双一流院校基础信息"""
import asyncio
import uuid
import sys
sys.path.insert(0, "backend")

from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import async_session
from app.models.university import University

UNIVERSITIES = [
    # ── 985 院校（39所） ──────────────────────────────────────────────
    # 北京
    {"name": "清华大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.tsinghua.edu.cn", "latitude": 39.9994, "longitude": 116.3267, "ranking": 1},
    {"name": "北京大学", "province": "北京", "city": "北京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.pku.edu.cn", "latitude": 39.9870, "longitude": 116.3052, "ranking": 2},
    {"name": "中国人民大学", "province": "北京", "city": "北京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ruc.edu.cn", "latitude": 39.9685, "longitude": 116.3196, "ranking": 8},
    {"name": "北京航空航天大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.buaa.edu.cn", "latitude": 39.9831, "longitude": 116.3474, "ranking": 16},
    {"name": "北京理工大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bit.edu.cn", "latitude": 39.9608, "longitude": 116.3164, "ranking": 26},
    {"name": "北京师范大学", "province": "北京", "city": "北京", "level": "985", "type": "师范",
     "tags": ["985", "211", "双一流"], "tuition_min": 4800, "tuition_max": 8000,
     "website": "https://www.bnu.edu.cn", "latitude": 39.9621, "longitude": 116.3575, "ranking": 12},
    {"name": "中国农业大学", "province": "北京", "city": "北京", "level": "985", "type": "农林",
     "tags": ["985", "211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.cau.edu.cn", "latitude": 40.0081, "longitude": 116.3543, "ranking": 34},
    {"name": "中央民族大学", "province": "北京", "city": "北京", "level": "985", "type": "民族",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.muc.edu.cn", "latitude": 39.9487, "longitude": 116.3328, "ranking": 38},
    # 上海
    {"name": "复旦大学", "province": "上海", "city": "上海", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5500, "tuition_max": 8500,
     "website": "https://www.fudan.edu.cn", "latitude": 31.2986, "longitude": 121.5034, "ranking": 3},
    {"name": "上海交通大学", "province": "上海", "city": "上海", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.sjtu.edu.cn", "latitude": 31.0282, "longitude": 121.4436, "ranking": 4},
    {"name": "同济大学", "province": "上海", "city": "上海", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.tongji.edu.cn", "latitude": 31.2837, "longitude": 121.5019, "ranking": 15},
    {"name": "华东师范大学", "province": "上海", "city": "上海", "level": "985", "type": "师范",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ecnu.edu.cn", "latitude": 31.2287, "longitude": 121.4063, "ranking": 35},
    # 天津
    {"name": "南开大学", "province": "天津", "city": "天津", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nankai.edu.cn", "latitude": 39.1152, "longitude": 117.1753, "ranking": 17},
    {"name": "天津大学", "province": "天津", "city": "天津", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.tju.edu.cn", "latitude": 39.1282, "longitude": 117.1858, "ranking": 18},
    # 辽宁
    {"name": "大连理工大学", "province": "辽宁", "city": "大连", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.dlut.edu.cn", "latitude": 38.8842, "longitude": 121.5297, "ranking": 25},
    {"name": "东北大学", "province": "辽宁", "city": "沈阳", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.neu.edu.cn", "latitude": 41.7698, "longitude": 123.4157, "ranking": 33},
    # 吉林
    {"name": "吉林大学", "province": "吉林", "city": "长春", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.jlu.edu.cn", "latitude": 43.8292, "longitude": 125.2743, "ranking": 24},
    # 黑龙江
    {"name": "哈尔滨工业大学", "province": "黑龙江", "city": "哈尔滨", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hit.edu.cn", "latitude": 45.7411, "longitude": 126.6278, "ranking": 13},
    # 江苏
    {"name": "南京大学", "province": "江苏", "city": "南京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5200, "tuition_max": 7800,
     "website": "https://www.nju.edu.cn", "latitude": 32.0579, "longitude": 118.7781, "ranking": 7},
    {"name": "东南大学", "province": "江苏", "city": "南京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.seu.edu.cn", "latitude": 32.0574, "longitude": 118.7899, "ranking": 20},
    # 浙江
    {"name": "浙江大学", "province": "浙江", "city": "杭州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.zju.edu.cn", "latitude": 30.3085, "longitude": 120.0864, "ranking": 5},
    # 安徽
    {"name": "中国科学技术大学", "province": "安徽", "city": "合肥", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4800, "tuition_max": 7000,
     "website": "https://www.ustc.edu.cn", "latitude": 31.8427, "longitude": 117.2654, "ranking": 6},
    # 福建
    {"name": "厦门大学", "province": "福建", "city": "厦门", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xmu.edu.cn", "latitude": 24.4365, "longitude": 118.0954, "ranking": 21},
    # 山东
    {"name": "山东大学", "province": "山东", "city": "济南", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdu.edu.cn", "latitude": 36.6687, "longitude": 116.9756, "ranking": 22},
    {"name": "中国海洋大学", "province": "山东", "city": "青岛", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ouc.edu.cn", "latitude": 36.0671, "longitude": 120.3826, "ranking": 36},
    # 湖北
    {"name": "武汉大学", "province": "湖北", "city": "武汉", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.whu.edu.cn", "latitude": 30.5378, "longitude": 114.3626, "ranking": 9},
    {"name": "华中科技大学", "province": "湖北", "city": "武汉", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hust.edu.cn", "latitude": 30.5115, "longitude": 114.4143, "ranking": 10},
    # 湖南
    {"name": "湖南大学", "province": "湖南", "city": "长沙", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hnu.edu.cn", "latitude": 28.1834, "longitude": 112.9465, "ranking": 30},
    {"name": "中南大学", "province": "湖南", "city": "长沙", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.csu.edu.cn", "latitude": 28.1633, "longitude": 112.9332, "ranking": 28},
    {"name": "国防科技大学", "province": "湖南", "city": "长沙", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 0, "tuition_max": 0,
     "website": "https://www.nudt.edu.cn", "latitude": 28.2362, "longitude": 112.9834, "ranking": 39},
    # 广东
    {"name": "中山大学", "province": "广东", "city": "广州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5160, "tuition_max": 8000,
     "website": "https://www.sysu.edu.cn", "latitude": 23.0934, "longitude": 113.2971, "ranking": 11},
    {"name": "华南理工大学", "province": "广东", "city": "广州", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.scut.edu.cn", "latitude": 23.1554, "longitude": 113.3518, "ranking": 23},
    # 重庆
    {"name": "重庆大学", "province": "重庆", "city": "重庆", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqu.edu.cn", "latitude": 29.5638, "longitude": 106.4689, "ranking": 31},
    # 四川
    {"name": "四川大学", "province": "四川", "city": "成都", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4440, "tuition_max": 7500,
     "website": "https://www.scu.edu.cn", "latitude": 30.6301, "longitude": 104.0826, "ranking": 19},
    {"name": "电子科技大学", "province": "四川", "city": "成都", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4900, "tuition_max": 8000,
     "website": "https://www.uestc.edu.cn", "latitude": 30.7592, "longitude": 103.9356, "ranking": 29},
    # 陕西
    {"name": "西安交通大学", "province": "陕西", "city": "西安", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.xjtu.edu.cn", "latitude": 34.2358, "longitude": 108.9872, "ranking": 14},
    {"name": "西北工业大学", "province": "陕西", "city": "西安", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.nwpu.edu.cn", "latitude": 34.2442, "longitude": 108.9103, "ranking": 27},
    {"name": "西北农林科技大学", "province": "陕西", "city": "杨凌", "level": "985", "type": "农林",
     "tags": ["985", "211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nwafu.edu.cn", "latitude": 34.2682, "longitude": 108.0742, "ranking": 37},
    # 甘肃
    {"name": "兰州大学", "province": "甘肃", "city": "兰州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.lzu.edu.cn", "latitude": 36.0514, "longitude": 103.8514, "ranking": 32},

    # ── 纯211院校（非985） ──────────────────────────────────────────
    # 北京
    {"name": "北京交通大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bjtu.edu.cn", "latitude": 39.9578, "longitude": 116.3478, "ranking": 41},
    {"name": "北京科技大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ustb.edu.cn", "latitude": 39.9853, "longitude": 116.3572, "ranking": 42},
    {"name": "北京化工大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.buct.edu.cn", "latitude": 40.0088, "longitude": 116.3977, "ranking": 51},
    {"name": "北京邮电大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bupt.edu.cn", "latitude": 39.9633, "longitude": 116.3567, "ranking": 40},
    {"name": "北京林业大学", "province": "北京", "city": "北京", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.bjfu.edu.cn", "latitude": 40.0088, "longitude": 116.3477, "ranking": 52},
    {"name": "北京中医药大学", "province": "北京", "city": "北京", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.bucm.edu.cn", "latitude": 39.9714, "longitude": 116.4075, "ranking": 53},
    {"name": "中国传媒大学", "province": "北京", "city": "北京", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cuc.edu.cn", "latitude": 39.9357, "longitude": 116.3953, "ranking": 50},
    {"name": "中央财经大学", "province": "北京", "city": "北京", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cufe.edu.cn", "latitude": 39.9572, "longitude": 116.3493, "ranking": 46},
    {"name": "对外经济贸易大学", "province": "北京", "city": "北京", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.uibe.edu.cn", "latitude": 39.9904, "longitude": 116.3922, "ranking": 47},
    {"name": "北京外国语大学", "province": "北京", "city": "北京", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bfsu.edu.cn", "latitude": 39.9622, "longitude": 116.3184, "ranking": 49},
    {"name": "中国政法大学", "province": "北京", "city": "北京", "level": "211", "type": "政法",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cupl.edu.cn", "latitude": 40.0096, "longitude": 116.3539, "ranking": 48},
    {"name": "华北电力大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ncepu.edu.cn", "latitude": 40.0577, "longitude": 116.2386, "ranking": 54},
    {"name": "中国矿业大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cumtb.edu.cn", "latitude": 39.9538, "longitude": 116.3568, "ranking": 57},
    {"name": "中国地质大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cugb.edu.cn", "latitude": 39.9719, "longitude": 116.3365, "ranking": 56},
    {"name": "中国石油大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cup.edu.cn", "latitude": 40.0678, "longitude": 116.2665, "ranking": 55},
    {"name": "北京体育大学", "province": "北京", "city": "北京", "level": "211", "type": "体育",
     "tags": ["211"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bsu.edu.cn", "latitude": 40.0652, "longitude": 116.3283, "ranking": None},
    # 上海
    {"name": "上海财经大学", "province": "上海", "city": "上海", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shufe.edu.cn", "latitude": 31.2239, "longitude": 121.4722, "ranking": 45},
    {"name": "上海外国语大学", "province": "上海", "city": "上海", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shisu.edu.cn", "latitude": 31.2056, "longitude": 121.4503, "ranking": 60},
    {"name": "上海大学", "province": "上海", "city": "上海", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shu.edu.cn", "latitude": 31.3174, "longitude": 121.4028, "ranking": None},
    {"name": "东华大学", "province": "上海", "city": "上海", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dhu.edu.cn", "latitude": 31.2294, "longitude": 121.4627, "ranking": 59},
    {"name": "华东理工大学", "province": "上海", "city": "上海", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ecust.edu.cn", "latitude": 31.1474, "longitude": 121.4033, "ranking": 58},
    # 天津
    {"name": "天津医科大学", "province": "天津", "city": "天津", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.tmu.edu.cn", "latitude": 39.1207, "longitude": 117.2015, "ranking": 105},
    # 河北
    {"name": "河北工业大学", "province": "河北", "city": "天津", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hebut.edu.cn", "latitude": 39.1502, "longitude": 117.1823, "ranking": 106},
    # 山西
    {"name": "太原理工大学", "province": "山西", "city": "太原", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tyut.edu.cn", "latitude": 37.8498, "longitude": 112.5562, "ranking": 87},
    # 内蒙古
    {"name": "内蒙古大学", "province": "内蒙古", "city": "呼和浩特", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.imu.edu.cn", "latitude": 40.8142, "longitude": 111.7476, "ranking": 95},
    # 辽宁
    {"name": "辽宁大学", "province": "辽宁", "city": "沈阳", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lnu.edu.cn", "latitude": 41.7228, "longitude": 123.4248, "ranking": 88},
    # 吉林
    {"name": "延边大学", "province": "吉林", "city": "延吉", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.ybu.edu.cn", "latitude": 42.8914, "longitude": 129.4842, "ranking": 91},
    # 黑龙江
    {"name": "哈尔滨工程大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hrbeu.edu.cn", "latitude": 45.7464, "longitude": 126.6186, "ranking": 92},
    {"name": "东北农业大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.neau.edu.cn", "latitude": 45.7434, "longitude": 126.7034, "ranking": 93},
    {"name": "东北林业大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nefu.edu.cn", "latitude": 45.7544, "longitude": 126.6403, "ranking": 94},
    # 江苏
    {"name": "苏州大学", "province": "江苏", "city": "苏州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.suda.edu.cn", "latitude": 31.3034, "longitude": 120.6403, "ranking": 61},
    {"name": "南京航空航天大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nuaa.edu.cn", "latitude": 32.0423, "longitude": 118.7984, "ranking": 43},
    {"name": "南京理工大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njust.edu.cn", "latitude": 32.0608, "longitude": 118.8344, "ranking": 44},
    {"name": "中国矿业大学", "province": "江苏", "city": "徐州", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cumt.edu.cn", "latitude": 34.2235, "longitude": 117.1442, "ranking": None},
    {"name": "河海大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.hhu.edu.cn", "latitude": 32.0614, "longitude": 118.7743, "ranking": 63},
    {"name": "南京农业大学", "province": "江苏", "city": "南京", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.njau.edu.cn", "latitude": 32.0425, "longitude": 118.8543, "ranking": 66},
    {"name": "南京师范大学", "province": "江苏", "city": "南京", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.nnu.edu.cn", "latitude": 32.1027, "longitude": 118.8775, "ranking": 62},
    {"name": "江南大学", "province": "江苏", "city": "无锡", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jiangnan.edu.cn", "latitude": 31.0534, "longitude": 120.2603, "ranking": 64},
    {"name": "中国药科大学", "province": "江苏", "city": "南京", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cpu.edu.cn", "latitude": 32.0472, "longitude": 118.8654, "ranking": 65},
    # 浙江
    # (浙江大学已在985中)
    # 安徽
    {"name": "安徽大学", "province": "安徽", "city": "合肥", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahu.edu.cn", "latitude": 31.7847, "longitude": 117.2784, "ranking": 85},
    # 福建
    {"name": "福州大学", "province": "福建", "city": "福州", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fzu.edu.cn", "latitude": 26.0674, "longitude": 119.1878, "ranking": 83},
    # 江西
    {"name": "南昌大学", "province": "江西", "city": "南昌", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ncu.edu.cn", "latitude": 28.6774, "longitude": 115.8662, "ranking": 86},
    # 山东
    {"name": "中国石油大学(华东)", "province": "山东", "city": "青岛", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.upc.edu.cn", "latitude": 36.0094, "longitude": 120.0964, "ranking": None},
    # 河南
    {"name": "郑州大学", "province": "河南", "city": "郑州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.zzu.edu.cn", "latitude": 34.7578, "longitude": 113.6634, "ranking": 79},
    # 湖北
    {"name": "武汉理工大学", "province": "湖北", "city": "武汉", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.whut.edu.cn", "latitude": 30.5154, "longitude": 114.4234, "ranking": 67},
    {"name": "中南财经政法大学", "province": "湖北", "city": "武汉", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zuel.edu.cn", "latitude": 30.4784, "longitude": 114.3614, "ranking": 69},
    {"name": "华中师范大学", "province": "湖北", "city": "武汉", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ccnu.edu.cn", "latitude": 30.4984, "longitude": 114.3644, "ranking": 68},
    {"name": "华中农业大学", "province": "湖北", "city": "武汉", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.hzau.edu.cn", "latitude": 30.4714, "longitude": 114.3654, "ranking": 71},
    {"name": "中国地质大学(武汉)", "province": "湖北", "city": "武汉", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cug.edu.cn", "latitude": 30.5214, "longitude": 114.4014, "ranking": 70},
    # 湖南
    {"name": "湖南师范大学", "province": "湖南", "city": "长沙", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.hunnu.edu.cn", "latitude": 28.1834, "longitude": 112.9395, "ranking": 80},
    # 广东
    {"name": "暨南大学", "province": "广东", "city": "广州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jnu.edu.cn", "latitude": 23.1254, "longitude": 113.3418, "ranking": 81},
    {"name": "华南师范大学", "province": "广东", "city": "广州", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.scnu.edu.cn", "latitude": 23.1558, "longitude": 113.3488, "ranking": 82},
    # 广西
    {"name": "广西大学", "province": "广西", "city": "南宁", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.gxu.edu.cn", "latitude": 22.8254, "longitude": 108.3178, "ranking": 102},
    # 海南
    {"name": "海南大学", "province": "海南", "city": "海口", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hainu.edu.cn", "latitude": 20.0444, "longitude": 110.3494, "ranking": 101},
    # 重庆
    {"name": "西南大学", "province": "重庆", "city": "重庆", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swu.edu.cn", "latitude": 29.5574, "longitude": 106.4684, "ranking": 72},
    # 四川
    {"name": "西南财经大学", "province": "四川", "city": "成都", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.swufe.edu.cn", "latitude": 30.6901, "longitude": 104.0626, "ranking": 73},
    {"name": "四川农业大学", "province": "四川", "city": "雅安", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.sicau.edu.cn", "latitude": 29.9734, "longitude": 103.0034, "ranking": None},
    # 贵州
    {"name": "贵州大学", "province": "贵州", "city": "贵阳", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gzu.edu.cn", "latitude": 26.4274, "longitude": 106.6714, "ranking": 103},
    # 云南
    {"name": "云南大学", "province": "云南", "city": "昆明", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynu.edu.cn", "latitude": 25.0424, "longitude": 102.8374, "ranking": 104},
    # 西藏
    {"name": "西藏大学", "province": "西藏", "city": "拉萨", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3000, "tuition_max": 5000,
     "website": "https://www.utibet.edu.cn", "latitude": 29.6514, "longitude": 91.1014, "ranking": 100},
    # 陕西
    {"name": "西北大学", "province": "陕西", "city": "西安", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nwu.edu.cn", "latitude": 34.2654, "longitude": 108.9054, "ranking": 77},
    {"name": "西安电子科技大学", "province": "陕西", "city": "西安", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.xidian.edu.cn", "latitude": 34.2454, "longitude": 108.9144, "ranking": 78},
    {"name": "陕西师范大学", "province": "陕西", "city": "西安", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.snnu.edu.cn", "latitude": 34.1644, "longitude": 108.9614, "ranking": 76},
    {"name": "长安大学", "province": "陕西", "city": "西安", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.chd.edu.cn", "latitude": 34.2374, "longitude": 108.9414, "ranking": 75},
    # 甘肃
    # (兰州大学已在985中)
    # 青海
    # 宁夏
    {"name": "宁夏大学", "province": "宁夏", "city": "银川", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nxu.edu.cn", "latitude": 38.4874, "longitude": 106.0774, "ranking": 98},
    # 新疆
    {"name": "新疆大学", "province": "新疆", "city": "乌鲁木齐", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.xju.edu.cn", "latitude": 43.7874, "longitude": 87.5974, "ranking": 96},
    {"name": "石河子大学", "province": "新疆", "city": "石河子", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.shzu.edu.cn", "latitude": 44.3074, "longitude": 86.0774, "ranking": 97},

    # ── 纯双一流院校（非985/非211） ─────────────────────────────────
    # 北京
    {"name": "中国科学院大学", "province": "北京", "city": "北京", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ucas.edu.cn", "latitude": 39.9834, "longitude": 116.3534, "ranking": 10},
    {"name": "首都师范大学", "province": "北京", "city": "北京", "level": "双一流", "type": "师范",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cnu.edu.cn", "latitude": 39.9684, "longitude": 116.2984, "ranking": 90},
    {"name": "外交学院", "province": "北京", "city": "北京", "level": "双一流", "type": "政法",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cfau.edu.cn", "latitude": 39.9374, "longitude": 116.3254, "ranking": 95},
    {"name": "中国人民公安大学", "province": "北京", "city": "北京", "level": "双一流", "type": "政法",
     "tags": ["双一流"], "tuition_min": 0, "tuition_max": 0,
     "website": "https://www.ppsuc.edu.cn", "latitude": 39.9414, "longitude": 116.3284, "ranking": 100},
    {"name": "中央音乐学院", "province": "北京", "city": "北京", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.ccom.edu.cn", "latitude": 39.9374, "longitude": 116.3534, "ranking": 90},
    # 上海
    {"name": "上海科技大学", "province": "上海", "city": "上海", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shanghaitech.edu.cn", "latitude": 31.0754, "longitude": 121.8324, "ranking": 55},
    {"name": "上海体育学院", "province": "上海", "city": "上海", "level": "双一流", "type": "体育",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shsus.edu.cn", "latitude": 31.2984, "longitude": 121.4744, "ranking": None},
    {"name": "上海音乐学院", "province": "上海", "city": "上海", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.shcmusic.edu.cn", "latitude": 31.2144, "longitude": 121.4624, "ranking": None},
    # 天津
    {"name": "天津工业大学", "province": "天津", "city": "天津", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tiangong.edu.cn", "latitude": 39.1304, "longitude": 117.1724, "ranking": 110},
    # 浙江
    {"name": "宁波大学", "province": "浙江", "city": "宁波", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.nbu.edu.cn", "latitude": 29.8744, "longitude": 121.5634, "ranking": 95},
    {"name": "中国美术学院", "province": "浙江", "city": "杭州", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.caa.edu.cn", "latitude": 30.1744, "longitude": 120.0624, "ranking": 85},
    # 江苏
    {"name": "南京邮电大学", "province": "江苏", "city": "南京", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njupt.edu.cn", "latitude": 32.0744, "longitude": 118.7744, "ranking": 85},
    {"name": "南京信息工程大学", "province": "江苏", "city": "南京", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nuist.edu.cn", "latitude": 32.1874, "longitude": 118.7124, "ranking": 80},
    # 江西
    {"name": "江西财经大学", "province": "江西", "city": "南昌", "level": "双一流", "type": "财经",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jxufe.edu.cn", "latitude": 28.7144, "longitude": 115.8744, "ranking": 115},
    # 河南
    {"name": "河南大学", "province": "河南", "city": "开封", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.henu.edu.cn", "latitude": 34.7844, "longitude": 114.3524, "ranking": 110},
    # 湖南
    {"name": "湘潭大学", "province": "湖南", "city": "湘潭", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xtu.edu.cn", "latitude": 27.8744, "longitude": 112.9374, "ranking": 105},
    # 广东
    {"name": "南方科技大学", "province": "广东", "city": "深圳", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sustech.edu.cn", "latitude": 22.5944, "longitude": 113.9744, "ranking": 50},
    {"name": "深圳大学", "province": "广东", "city": "深圳", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.szu.edu.cn", "latitude": 22.5344, "longitude": 113.9374, "ranking": 65},
    {"name": "华南农业大学", "province": "广东", "city": "广州", "level": "双一流", "type": "农林",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.scau.edu.cn", "latitude": 23.1644, "longitude": 113.3544, "ranking": 113},
    {"name": "广州医科大学", "province": "广东", "city": "广州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gzhmu.edu.cn", "latitude": 23.1244, "longitude": 113.2644, "ranking": 112},
    {"name": "广州中医药大学", "province": "广东", "city": "广州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gzucm.edu.cn", "latitude": 23.0744, "longitude": 113.3344, "ranking": 118},
    # 四川
    {"name": "成都理工大学", "province": "四川", "city": "成都", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cdut.edu.cn", "latitude": 30.6744, "longitude": 104.1344, "ranking": 100},
    {"name": "西南石油大学", "province": "四川", "city": "成都", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swpu.edu.cn", "latitude": 30.7144, "longitude": 104.1544, "ranking": 108},
    {"name": "成都中医药大学", "province": "四川", "city": "成都", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cdutcm.edu.cn", "latitude": 30.6844, "longitude": 104.0644, "ranking": 105},
    {"name": "西南医科大学", "province": "四川", "city": "泸州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.swmu.edu.cn", "latitude": 28.8944, "longitude": 105.4344, "ranking": None},
    # 重庆
    {"name": "重庆医科大学", "province": "重庆", "city": "重庆", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cqmu.edu.cn", "latitude": 29.5644, "longitude": 106.4744, "ranking": 120},
    # 黑龙江
    {"name": "哈尔滨医科大学", "province": "黑龙江", "city": "哈尔滨", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hmu.edu.cn", "latitude": 45.7344, "longitude": 126.6244, "ranking": None},
    # 山西
    {"name": "山西大学", "province": "山西", "city": "太原", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sxu.edu.cn", "latitude": 37.7944, "longitude": 112.5744, "ranking": 120},
    # 青海
    {"name": "青海大学", "province": "青海", "city": "西宁", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.qhu.edu.cn", "latitude": 36.6144, "longitude": 101.7544, "ranking": 99},

    # ── 普通本科院校（省属重点/知名公办） ───────────────────────────
    # 北京
    {"name": "首都经济贸易大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cueb.edu.cn", "latitude": 39.8644, "longitude": 116.3544, "ranking": None},
    {"name": "北京工商大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.btbu.edu.cn", "latitude": 39.8944, "longitude": 116.3144, "ranking": None},
    {"name": "北京建筑大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bucea.edu.cn", "latitude": 39.9244, "longitude": 116.2844, "ranking": 148},
    {"name": "北京第二外国语学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "语言",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bisu.edu.cn", "latitude": 39.9144, "longitude": 116.5544, "ranking": 145},
    {"name": "北方工业大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ncut.edu.cn", "latitude": 39.9344, "longitude": 116.2244, "ranking": 155},
    # 上海
    {"name": "上海理工大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.usst.edu.cn", "latitude": 31.2744, "longitude": 121.4744, "ranking": 110},
    {"name": "上海师范大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shnu.edu.cn", "latitude": 31.1744, "longitude": 121.4144, "ranking": 120},
    {"name": "上海海事大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shmtu.edu.cn", "latitude": 31.0644, "longitude": 121.8344, "ranking": 135},
    {"name": "上海对外经贸大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.suibe.edu.cn", "latitude": 31.2344, "longitude": 121.4244, "ranking": None},
    {"name": "上海工程技术大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sues.edu.cn", "latitude": 31.2644, "longitude": 121.2144, "ranking": 155},
    # 天津
    {"name": "天津师范大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tjnu.edu.cn", "latitude": 39.0844, "longitude": 117.1644, "ranking": 140},
    {"name": "天津科技大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tust.edu.cn", "latitude": 39.1144, "longitude": 117.2144, "ranking": 155},
    {"name": "天津理工大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tjut.edu.cn", "latitude": 39.1044, "longitude": 117.1744, "ranking": 150},
    # 河北
    {"name": "河北大学", "province": "河北", "city": "保定", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hbu.edu.cn", "latitude": 38.7644, "longitude": 115.2744, "ranking": 130},
    {"name": "燕山大学", "province": "河北", "city": "秦皇岛", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ysu.edu.cn", "latitude": 39.9644, "longitude": 119.5244, "ranking": 100},
    {"name": "河北师范大学", "province": "河北", "city": "石家庄", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hebtu.edu.cn", "latitude": 38.0744, "longitude": 114.4744, "ranking": 140},
    {"name": "河北医科大学", "province": "河北", "city": "石家庄", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hebmu.edu.cn", "latitude": 38.0344, "longitude": 114.4844, "ranking": None},
    # 山西
    {"name": "中北大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nuc.edu.cn", "latitude": 37.8444, "longitude": 112.5144, "ranking": 145},
    {"name": "山西医科大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.sxmu.edu.cn", "latitude": 37.8644, "longitude": 112.5744, "ranking": None},
    {"name": "山西师范大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sxnu.edu.cn", "latitude": 37.8144, "longitude": 112.5344, "ranking": None},
    # 内蒙古
    {"name": "内蒙古师范大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.imnu.edu.cn", "latitude": 40.8344, "longitude": 111.7544, "ranking": None},
    {"name": "内蒙古医科大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.immu.edu.cn", "latitude": 40.7944, "longitude": 111.7244, "ranking": None},
    # 辽宁
    {"name": "辽宁师范大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lnnu.edu.cn", "latitude": 38.8744, "longitude": 121.5144, "ranking": None},
    {"name": "沈阳工业大学", "province": "辽宁", "city": "沈阳", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sut.edu.cn", "latitude": 41.7744, "longitude": 123.3744, "ranking": 155},
    {"name": "大连大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.dlu.edu.cn", "latitude": 38.8944, "longitude": 121.6844, "ranking": None},
    # 吉林
    {"name": "长春理工大学", "province": "吉林", "city": "长春", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cust.edu.cn", "latitude": 43.8544, "longitude": 125.2944, "ranking": 130},
    {"name": "东北电力大学", "province": "吉林", "city": "吉林", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nepu.edu.cn", "latitude": 43.8344, "longitude": 126.5244, "ranking": 145},
    {"name": "吉林师范大学", "province": "吉林", "city": "四平", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.jlnu.edu.cn", "latitude": 43.1744, "longitude": 124.3744, "ranking": None},
    # 黑龙江
    {"name": "黑龙江大学", "province": "黑龙江", "city": "哈尔滨", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 8000,
     "website": "https://www.hljtu.edu.cn", "latitude": 45.7344, "longitude": 126.6144, "ranking": 130},
    {"name": "齐齐哈尔大学", "province": "黑龙江", "city": "齐齐哈尔", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.qqhru.edu.cn", "latitude": 47.3544, "longitude": 123.9544, "ranking": None},
    # 江苏
    {"name": "扬州大学", "province": "江苏", "city": "扬州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.yzu.edu.cn", "latitude": 32.3944, "longitude": 119.4244, "ranking": 115},
    {"name": "江苏大学", "province": "江苏", "city": "镇江", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ujs.edu.cn", "latitude": 32.2044, "longitude": 119.4544, "ranking": 105},
    {"name": "南京工业大学", "province": "江苏", "city": "南京", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njtech.edu.cn", "latitude": 32.0644, "longitude": 118.7844, "ranking": 100},
    {"name": "江苏师范大学", "province": "江苏", "city": "徐州", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jsnu.edu.cn", "latitude": 34.2244, "longitude": 117.1844, "ranking": None},
    {"name": "常州大学", "province": "江苏", "city": "常州", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cczu.edu.cn", "latitude": 31.7544, "longitude": 119.9244, "ranking": None},
    # 浙江
    {"name": "浙江工业大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjut.edu.cn", "latitude": 30.2144, "longitude": 120.0644, "ranking": 100},
    {"name": "浙江师范大学", "province": "浙江", "city": "金华", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjnu.edu.cn", "latitude": 29.0144, "longitude": 119.6344, "ranking": 120},
    {"name": "浙江理工大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zstu.edu.cn", "latitude": 30.1744, "longitude": 120.2144, "ranking": None},
    {"name": "浙江工商大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjgsu.edu.cn", "latitude": 30.2644, "longitude": 120.1544, "ranking": None},
    {"name": "温州大学", "province": "浙江", "city": "温州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.wzu.edu.cn", "latitude": 28.0144, "longitude": 120.6344, "ranking": None},
    # 安徽
    {"name": "安徽师范大学", "province": "安徽", "city": "芜湖", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahnu.edu.cn", "latitude": 31.3344, "longitude": 118.3844, "ranking": 135},
    {"name": "安徽工业大学", "province": "安徽", "city": "马鞍山", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahut.edu.cn", "latitude": 31.6744, "longitude": 118.5144, "ranking": 160},
    {"name": "安徽理工大学", "province": "安徽", "city": "淮南", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.aust.edu.cn", "latitude": 32.6344, "longitude": 116.9744, "ranking": None},
    {"name": "安徽医科大学", "province": "安徽", "city": "合肥", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.ahmu.edu.cn", "latitude": 31.8144, "longitude": 117.2744, "ranking": None},
    # 福建
    {"name": "福建师范大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fjnu.edu.cn", "latitude": 26.0744, "longitude": 119.2944, "ranking": 120},
    {"name": "华侨大学", "province": "福建", "city": "泉州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hqu.edu.cn", "latitude": 24.8744, "longitude": 118.6744, "ranking": 130},
    {"name": "福建医科大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.fjmu.edu.cn", "latitude": 26.0444, "longitude": 119.2644, "ranking": None},
    {"name": "福建农林大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fafu.edu.cn", "latitude": 26.0344, "longitude": 119.2344, "ranking": None},
    # 江西
    {"name": "江西师范大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.jxnu.edu.cn", "latitude": 28.6844, "longitude": 115.8544, "ranking": 140},
    {"name": "南昌航空大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nchu.edu.cn", "latitude": 28.6944, "longitude": 115.8744, "ranking": 150},
    # 山东
    {"name": "山东师范大学", "province": "山东", "city": "济南", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdnu.edu.cn", "latitude": 36.6544, "longitude": 116.9544, "ranking": 125},
    {"name": "青岛大学", "province": "山东", "city": "青岛", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.qdu.edu.cn", "latitude": 36.0744, "longitude": 120.3744, "ranking": 120},
    {"name": "济南大学", "province": "山东", "city": "济南", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ujn.edu.cn", "latitude": 36.6744, "longitude": 116.9644, "ranking": 145},
    {"name": "山东科技大学", "province": "山东", "city": "青岛", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdust.edu.cn", "latitude": 36.0044, "longitude": 120.1144, "ranking": 130},
    {"name": "山东农业大学", "province": "山东", "city": "泰安", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdau.edu.cn", "latitude": 36.1644, "longitude": 117.1544, "ranking": None},
    # 河南
    {"name": "河南师范大学", "province": "河南", "city": "新乡", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.htu.edu.cn", "latitude": 35.3044, "longitude": 113.9244, "ranking": 145},
    {"name": "河南科技大学", "province": "河南", "city": "洛阳", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.haust.edu.cn", "latitude": 34.6244, "longitude": 112.4244, "ranking": 155},
    {"name": "河南理工大学", "province": "河南", "city": "焦作", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hpu.edu.cn", "latitude": 35.2244, "longitude": 113.2444, "ranking": None},
    {"name": "河南农业大学", "province": "河南", "city": "郑州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.henau.edu.cn", "latitude": 34.7644, "longitude": 113.6544, "ranking": None},
    # 湖北
    {"name": "湖北大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hubu.edu.cn", "latitude": 30.5644, "longitude": 114.3844, "ranking": 130},
    {"name": "武汉科技大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.wust.edu.cn", "latitude": 30.4344, "longitude": 114.3944, "ranking": 135},
    {"name": "三峡大学", "province": "湖北", "city": "宜昌", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ctgu.edu.cn", "latitude": 30.7244, "longitude": 111.3044, "ranking": 155},
    {"name": "长江大学", "province": "湖北", "city": "荆州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.yangtzeu.edu.cn", "latitude": 30.3444, "longitude": 112.2044, "ranking": None},
    # 湖南
    {"name": "长沙理工大学", "province": "湖南", "city": "长沙", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.csust.edu.cn", "latitude": 28.1544, "longitude": 112.9344, "ranking": 130},
    {"name": "湖南科技大学", "province": "湖南", "city": "湘潭", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hnust.edu.cn", "latitude": 27.8944, "longitude": 112.9244, "ranking": 150},
    {"name": "湖南农业大学", "province": "湖南", "city": "长沙", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hunau.edu.cn", "latitude": 28.1844, "longitude": 112.9544, "ranking": None},
    # 广东
    {"name": "广东工业大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gdut.edu.cn", "latitude": 23.1444, "longitude": 113.3744, "ranking": 120},
    {"name": "广东外语外贸大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "语言",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gdufs.edu.cn", "latitude": 23.1044, "longitude": 113.2744, "ranking": 110},
    {"name": "广州大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gzhu.edu.cn", "latitude": 23.0644, "longitude": 113.3544, "ranking": 130},
    {"name": "汕头大学", "province": "广东", "city": "汕头", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.stu.edu.cn", "latitude": 23.3544, "longitude": 116.6344, "ranking": None},
    {"name": "东莞理工学院", "province": "广东", "city": "东莞", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dgut.edu.cn", "latitude": 22.9544, "longitude": 113.8844, "ranking": None},
    {"name": "广东医科大学", "province": "广东", "city": "湛江", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gdmu.edu.cn", "latitude": 21.2644, "longitude": 110.3144, "ranking": 150},
    # 广西
    {"name": "广西师范大学", "province": "广西", "city": "桂林", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.gxnu.edu.cn", "latitude": 25.2744, "longitude": 110.3144, "ranking": 140},
    {"name": "桂林电子科技大学", "province": "广西", "city": "桂林", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.guet.edu.cn", "latitude": 25.2644, "longitude": 110.3244, "ranking": 145},
    {"name": "广西医科大学", "province": "广西", "city": "南宁", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gxmu.edu.cn", "latitude": 22.8244, "longitude": 108.3244, "ranking": None},
    # 海南
    {"name": "海南师范大学", "province": "海南", "city": "海口", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hainnu.edu.cn", "latitude": 20.0144, "longitude": 110.3344, "ranking": 155},
    # 重庆
    {"name": "重庆邮电大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqupt.edu.cn", "latitude": 29.5244, "longitude": 106.4644, "ranking": 130},
    {"name": "重庆交通大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqjtu.edu.cn", "latitude": 29.5744, "longitude": 106.4944, "ranking": 145},
    # 四川
    {"name": "四川师范大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sicnu.edu.cn", "latitude": 30.6544, "longitude": 104.0644, "ranking": None},
    {"name": "成都信息工程大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cuit.edu.cn", "latitude": 30.5644, "longitude": 103.9844, "ranking": 140},
    {"name": "西南民族大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "民族",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swun.edu.cn", "latitude": 30.5844, "longitude": 104.0444, "ranking": 140},
    {"name": "成都大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cdu.edu.cn", "latitude": 30.6844, "longitude": 104.1744, "ranking": 155},
    # 贵州
    {"name": "贵州师范大学", "province": "贵州", "city": "贵阳", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gznu.edu.cn", "latitude": 26.5444, "longitude": 106.7144, "ranking": 160},
    {"name": "贵州医科大学", "province": "贵州", "city": "贵阳", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gmu.edu.cn", "latitude": 26.4144, "longitude": 106.6644, "ranking": 155},
    # 云南
    {"name": "昆明理工大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.kust.edu.cn", "latitude": 25.0444, "longitude": 102.8244, "ranking": 120},
    {"name": "云南师范大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynnu.edu.cn", "latitude": 25.0144, "longitude": 102.7844, "ranking": 150},
    {"name": "云南农业大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynau.edu.cn", "latitude": 25.0444, "longitude": 102.7344, "ranking": 170},
    # 陕西
    {"name": "西安建筑科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xauat.edu.cn", "latitude": 34.2444, "longitude": 108.9044, "ranking": 125},
    {"name": "西安理工大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xaut.edu.cn", "latitude": 34.2544, "longitude": 108.9544, "ranking": 135},
    {"name": "陕西科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sust.edu.cn", "latitude": 34.2144, "longitude": 108.9444, "ranking": 155},
    {"name": "西安科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xust.edu.cn", "latitude": 34.2344, "longitude": 108.9244, "ranking": 160},
    # 甘肃
    {"name": "西北师范大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.nwnu.edu.cn", "latitude": 36.0744, "longitude": 103.8244, "ranking": 130},
    {"name": "兰州理工大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lut.edu.cn", "latitude": 36.0444, "longitude": 103.8044, "ranking": 150},
    {"name": "甘肃农业大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gsau.edu.cn", "latitude": 36.0544, "longitude": 103.8344, "ranking": 170},
    # 青海
    {"name": "青海师范大学", "province": "青海", "city": "西宁", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.qhnu.edu.cn", "latitude": 36.5944, "longitude": 101.7244, "ranking": 175},
    # 宁夏
    {"name": "宁夏医科大学", "province": "宁夏", "city": "银川", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.nxmu.edu.cn", "latitude": 38.4744, "longitude": 106.0744, "ranking": 165},
    # 新疆
    {"name": "新疆师范大学", "province": "新疆", "city": "乌鲁木齐", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.xjnnu.edu.cn", "latitude": 43.7944, "longitude": 87.5944, "ranking": 170},
    {"name": "新疆医科大学", "province": "新疆", "city": "乌鲁木齐", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.xjmu.edu.cn", "latitude": 43.7744, "longitude": 87.6144, "ranking": 155},

    # ── 补充院校 ─────────────────────────────────────────────
    # 北京补充
    {"name": "北京物资学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bwu.edu.cn", "latitude": 39.9044, "longitude": 116.6544, "ranking": 180},
    {"name": "中国劳动关系学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "政法",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.culr.edu.cn", "latitude": 39.9344, "longitude": 116.3344, "ranking": 175},
    {"name": "中国青年政治学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "政法",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cyu.edu.cn", "latitude": 39.9244, "longitude": 116.3244, "ranking": 170},
    {"name": "北京服装学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "艺术",
     "tags": [], "tuition_min": 10000, "tuition_max": 15000,
     "website": "https://www.bift.edu.cn", "latitude": 39.9644, "longitude": 116.3644, "ranking": 185},
    {"name": "北京印刷学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bigc.edu.cn", "latitude": 39.7944, "longitude": 116.3344, "ranking": 190},
    {"name": "北京石油化工学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bipt.edu.cn", "latitude": 39.7644, "longitude": 116.3344, "ranking": 195},
    {"name": "首都体育学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "体育",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cupes.edu.cn", "latitude": 39.9844, "longitude": 116.3544, "ranking": 200},
    # 上海补充
    {"name": "上海海关学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "政法",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shcc.edu.cn", "latitude": 31.2244, "longitude": 121.5344, "ranking": 160},
    {"name": "上海立信会计金融学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.lixin.edu.cn", "latitude": 31.1644, "longitude": 121.4344, "ranking": 155},
    {"name": "上海电机学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.sdju.edu.cn", "latitude": 31.0844, "longitude": 121.4344, "ranking": 195},
    {"name": "上海商学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.sbs.edu.cn", "latitude": 31.1844, "longitude": 121.4344, "ranking": 190},
    {"name": "上海政法学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "政法",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.shupl.edu.cn", "latitude": 31.1144, "longitude": 121.1844, "ranking": 175},
    {"name": "上海第二工业大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.sspu.edu.cn", "latitude": 31.2244, "longitude": 121.6344, "ranking": 200},
    # 广东补充
    {"name": "广东金融学院", "province": "广东", "city": "广州", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.gduf.edu.cn", "latitude": 23.1844, "longitude": 113.3544, "ranking": 165},
    {"name": "东莞理工学院", "province": "广东", "city": "东莞", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.dgut.edu.cn", "latitude": 23.0244, "longitude": 113.7444, "ranking": 180},
    {"name": "佛山科学技术学院", "province": "广东", "city": "佛山", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.fosu.edu.cn", "latitude": 23.0244, "longitude": 113.1244, "ranking": 185},
    {"name": "仲恺农业工程学院", "province": "广东", "city": "广州", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.zhku.edu.cn", "latitude": 23.1044, "longitude": 113.2944, "ranking": 195},
    {"name": "五邑大学", "province": "广东", "city": "江门", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.wyu.edu.cn", "latitude": 22.5844, "longitude": 113.0844, "ranking": 190},
    {"name": "肇庆学院", "province": "广东", "city": "肇庆", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.zqu.edu.cn", "latitude": 23.0744, "longitude": 112.4644, "ranking": 200},
    {"name": "惠州学院", "province": "广东", "city": "惠州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5500, "tuition_max": 10000,
     "website": "https://www.hzu.edu.cn", "latitude": 23.0844, "longitude": 114.4144, "ranking": 205},
    # 江苏补充
    {"name": "常州大学", "province": "江苏", "city": "常州", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.cczu.edu.cn", "latitude": 31.7744, "longitude": 119.9744, "ranking": 155},
    {"name": "徐州医科大学", "province": "江苏", "city": "徐州", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 6000, "tuition_max": 9000,
     "website": "https://www.xzhmu.edu.cn", "latitude": 34.2644, "longitude": 117.1844, "ranking": 145},
    {"name": "江苏科技大学", "province": "江苏", "city": "镇江", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.just.edu.cn", "latitude": 32.1944, "longitude": 119.4544, "ranking": 160},
    {"name": "盐城工学院", "province": "江苏", "city": "盐城", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.ycit.edu.cn", "latitude": 33.3844, "longitude": 120.1644, "ranking": 195},
    {"name": "淮阴工学院", "province": "江苏", "city": "淮安", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.hyit.edu.cn", "latitude": 33.5944, "longitude": 119.0144, "ranking": 200},
    # 浙江补充
    {"name": "浙江理工大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.zstu.edu.cn", "latitude": 30.2844, "longitude": 120.1544, "ranking": 120},
    {"name": "浙江工商大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.zjgsu.edu.cn", "latitude": 30.2944, "longitude": 120.1844, "ranking": 115},
    {"name": "中国计量大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cjlu.edu.cn", "latitude": 30.3044, "longitude": 120.3444, "ranking": 125},
    {"name": "温州大学", "province": "浙江", "city": "温州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.wzu.edu.cn", "latitude": 28.0044, "longitude": 120.6944, "ranking": 155},
    {"name": "浙江农林大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.zafu.edu.cn", "latitude": 30.2644, "longitude": 119.7244, "ranking": 170},
    # 湖北补充
    {"name": "长江大学", "province": "湖北", "city": "荆州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.yangtzeeu.edu.cn", "latitude": 30.3344, "longitude": 112.2444, "ranking": 150},
    {"name": "湖北中医药大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.hbtcm.edu.cn", "latitude": 30.5244, "longitude": 114.3344, "ranking": 165},
    {"name": "武汉纺织大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.wtu.edu.cn", "latitude": 30.4844, "longitude": 114.3844, "ranking": 170},
    {"name": "武汉轻工大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.whpu.edu.cn", "latitude": 30.6344, "longitude": 114.2244, "ranking": 175},
    # 四川补充
    {"name": "四川农业大学", "province": "四川", "city": "雅安", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.sicau.edu.cn", "latitude": 29.9844, "longitude": 103.0044, "ranking": 107},
    {"name": "成都医学院", "province": "四川", "city": "成都", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cmc.edu.cn", "latitude": 30.7344, "longitude": 104.0644, "ranking": 180},
    {"name": "绵阳师范学院", "province": "四川", "city": "绵阳", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.mnu.edu.cn", "latitude": 31.4744, "longitude": 104.7344, "ranking": 200},
    {"name": "宜宾学院", "province": "四川", "city": "宜宾", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ybu.edu.cn", "latitude": 28.7744, "longitude": 104.6344, "ranking": 210},
    {"name": "乐山师范学院", "province": "四川", "city": "乐山", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.lsnu.edu.cn", "latitude": 29.5744, "longitude": 103.7644, "ranking": 205},
    # 山东补充
    {"name": "齐鲁工业大学", "province": "山东", "city": "济南", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.qlu.edu.cn", "latitude": 36.6544, "longitude": 116.9844, "ranking": 150},
    {"name": "山东理工大学", "province": "山东", "city": "淄博", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sdut.edu.cn", "latitude": 36.8144, "longitude": 118.0544, "ranking": 165},
    {"name": "聊城大学", "province": "山东", "city": "聊城", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.lcu.edu.cn", "latitude": 36.4544, "longitude": 115.9844, "ranking": 180},
    {"name": "鲁东大学", "province": "山东", "city": "烟台", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ldu.edu.cn", "latitude": 37.5144, "longitude": 121.3844, "ranking": 175},
    # 福建补充
    {"name": "福建农林大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.fafu.edu.cn", "latitude": 26.0844, "longitude": 119.2344, "ranking": 140},
    {"name": "福建医科大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 6000, "tuition_max": 9000,
     "website": "https://www.fjmu.edu.cn", "latitude": 26.0744, "longitude": 119.2944, "ranking": 135},
    {"name": "福建中医药大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 6000, "tuition_max": 9000,
     "website": "https://www.fjtcm.edu.cn", "latitude": 26.0944, "longitude": 119.3144, "ranking": 160},
    {"name": "闽南师范大学", "province": "福建", "city": "漳州", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.mnnu.edu.cn", "latitude": 24.5144, "longitude": 117.6544, "ranking": 185},
    # 河南补充
    {"name": "河南理工大学", "province": "河南", "city": "焦作", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.hpu.edu.cn", "latitude": 35.2144, "longitude": 113.2444, "ranking": 155},
    {"name": "河南农业大学", "province": "河南", "city": "郑州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.henau.edu.cn", "latitude": 34.7944, "longitude": 113.6744, "ranking": 165},
    {"name": "河南中医药大学", "province": "河南", "city": "郑州", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.hactcm.edu.cn", "latitude": 34.7644, "longitude": 113.6944, "ranking": 170},
    {"name": "信阳师范大学", "province": "河南", "city": "信阳", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.xynu.edu.cn", "latitude": 32.1244, "longitude": 114.0944, "ranking": 180},
    # 湖南补充
    {"name": "吉首大学", "province": "湖南", "city": "吉首", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.jsu.edu.cn", "latitude": 28.3144, "longitude": 109.7344, "ranking": 185},
    {"name": "湖南工业大学", "province": "湖南", "city": "株洲", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.hut.edu.cn", "latitude": 27.8344, "longitude": 113.1344, "ranking": 175},
    {"name": "湖南农业大学", "province": "湖南", "city": "长沙", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.hunau.edu.cn", "latitude": 28.1844, "longitude": 113.0844, "ranking": 155},
    # 陕西补充
    {"name": "延安大学", "province": "陕西", "city": "延安", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.yau.edu.cn", "latitude": 36.6044, "longitude": 109.4844, "ranking": 170},
    {"name": "陕西理工大学", "province": "陕西", "city": "汉中", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.snut.edu.cn", "latitude": 33.0744, "longitude": 107.0244, "ranking": 195},
    {"name": "宝鸡文理学院", "province": "陕西", "city": "宝鸡", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.bjwlxy.edu.cn", "latitude": 34.3744, "longitude": 107.2344, "ranking": 210},
    # 辽宁补充
    {"name": "大连外国语大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "语言",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dlufl.edu.cn", "latitude": 38.8944, "longitude": 121.5544, "ranking": 150},
    {"name": "沈阳药科大学", "province": "辽宁", "city": "沈阳", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.syphu.edu.cn", "latitude": 41.7844, "longitude": 123.4244, "ranking": 140},
    {"name": "大连民族大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "民族",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dlnu.edu.cn", "latitude": 39.0344, "longitude": 121.8444, "ranking": 190},
    # 吉林补充
    {"name": "长春工业大学", "province": "吉林", "city": "长春", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ccut.edu.cn", "latitude": 43.8844, "longitude": 125.3244, "ranking": 175},
    {"name": "吉林农业大学", "province": "吉林", "city": "长春", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.jlau.edu.cn", "latitude": 43.8344, "longitude": 125.4144, "ranking": 165},
    # 黑龙江补充
    {"name": "哈尔滨师范大学", "province": "黑龙江", "city": "哈尔滨", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.hrbnu.edu.cn", "latitude": 45.7344, "longitude": 126.6344, "ranking": 140},
    {"name": "哈尔滨医科大学", "province": "黑龙江", "city": "哈尔滨", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hrbmu.edu.cn", "latitude": 45.7244, "longitude": 126.6244, "ranking": 125},
    {"name": "东北石油大学", "province": "黑龙江", "city": "大庆", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.nepu.edu.cn", "latitude": 46.5944, "longitude": 125.0844, "ranking": 155},
    # 安徽补充
    {"name": "安徽医科大学", "province": "安徽", "city": "合肥", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.ahmu.edu.cn", "latitude": 31.8344, "longitude": 117.2644, "ranking": 130},
    {"name": "安徽农业大学", "province": "安徽", "city": "合肥", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ahau.edu.cn", "latitude": 31.8444, "longitude": 117.2844, "ranking": 160},
    {"name": "淮北师范大学", "province": "安徽", "city": "淮北", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.chnu.edu.cn", "latitude": 33.9744, "longitude": 116.7944, "ranking": 185},
    # 山西补充
    {"name": "山西医科大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sxmu.edu.cn", "latitude": 37.8744, "longitude": 112.5544, "ranking": 145},
    {"name": "太原科技大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.tyust.edu.cn", "latitude": 37.8844, "longitude": 112.5144, "ranking": 185},
    # 河北补充
    {"name": "河北科技大学", "province": "河北", "city": "石家庄", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.hebust.edu.cn", "latitude": 38.0444, "longitude": 114.4944, "ranking": 180},
    {"name": "华北科技学院", "province": "河北", "city": "廊坊", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ncist.edu.cn", "latitude": 39.9544, "longitude": 116.8144, "ranking": 190},
    # 江西补充
    {"name": "江西中医药大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jxutcm.edu.cn", "latitude": 28.6844, "longitude": 115.8944, "ranking": 165},
    {"name": "江西农业大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.jxau.edu.cn", "latitude": 28.7744, "longitude": 115.8444, "ranking": 170},
    # 广西补充
    {"name": "广西医科大学", "province": "广西", "city": "南宁", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gxmu.edu.cn", "latitude": 22.8244, "longitude": 108.3644, "ranking": 140},
    {"name": "桂林理工大学", "province": "广西", "city": "桂林", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.glut.edu.cn", "latitude": 25.2744, "longitude": 110.2944, "ranking": 180},
    # 重庆补充
    {"name": "重庆理工大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqut.edu.cn", "latitude": 29.4744, "longitude": 106.5244, "ranking": 160},
    {"name": "重庆工商大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ctbu.edu.cn", "latitude": 29.5344, "longitude": 106.5844, "ranking": 155},
    # 天津补充
    {"name": "天津外国语大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "语言",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.tjfsu.edu.cn", "latitude": 39.1144, "longitude": 117.2144, "ranking": 155},
    {"name": "天津商业大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.tjcu.edu.cn", "latitude": 39.1344, "longitude": 117.1544, "ranking": 175},
    {"name": "天津农学院", "province": "天津", "city": "天津", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.tjau.edu.cn", "latitude": 39.1544, "longitude": 117.0144, "ranking": 205},
    # 云南补充
    {"name": "云南财经大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynufe.edu.cn", "latitude": 25.0544, "longitude": 102.7144, "ranking": 160},
    {"name": "大理大学", "province": "云南", "city": "大理", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.dali.edu.cn", "latitude": 25.5944, "longitude": 100.2344, "ranking": 190},
    # 贵州补充
    {"name": "贵州财经大学", "province": "贵州", "city": "贵阳", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.gufe.edu.cn", "latitude": 26.6144, "longitude": 106.7244, "ranking": 185},
    {"name": "遵义医科大学", "province": "贵州", "city": "遵义", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zmu.edu.cn", "latitude": 27.7244, "longitude": 106.9244, "ranking": 175},
    # 甘肃补充
    {"name": "兰州交通大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.lzjtu.edu.cn", "latitude": 36.0744, "longitude": 103.8544, "ranking": 160},
    {"name": "甘肃政法大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "政法",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gsli.edu.cn", "latitude": 36.0944, "longitude": 103.8444, "ranking": 185},
    # 内蒙古补充
    {"name": "内蒙古医科大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.immu.edu.cn", "latitude": 40.8444, "longitude": 111.7544, "ranking": 175},
    {"name": "内蒙古师范大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.imnu.edu.cn", "latitude": 40.8244, "longitude": 111.7244, "ranking": 170},
    # 宁夏补充
    {"name": "北方民族大学", "province": "宁夏", "city": "银川", "level": "普通本科", "type": "民族",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.nmu.edu.cn", "latitude": 38.4944, "longitude": 106.2244, "ranking": 185},
    {"name": "宁夏大学", "province": "宁夏", "city": "银川", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.nxu.edu.cn", "latitude": 38.4744, "longitude": 106.2744, "ranking": 98},
    # 青海补充
    {"name": "青海大学", "province": "青海", "city": "西宁", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.qhu.edu.cn", "latitude": 36.6144, "longitude": 101.7544, "ranking": 99},
    # 西藏补充
    {"name": "西藏大学", "province": "西藏", "city": "拉萨", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3000, "tuition_max": 5500,
     "website": "https://www.utibet.edu.cn", "latitude": 29.6544, "longitude": 91.1344, "ranking": 100},
    # 新疆补充
    {"name": "石河子大学", "province": "新疆", "city": "石河子", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.shzu.edu.cn", "latitude": 44.3044, "longitude": 86.0444, "ranking": 97},
    {"name": "新疆农业大学", "province": "新疆", "city": "乌鲁木齐", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.xjau.edu.cn", "latitude": 43.7844, "longitude": 87.5744, "ranking": 185},
    # 海南补充
    {"name": "海南大学", "province": "海南", "city": "海口", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.hainu.edu.cn", "latitude": 20.0544, "longitude": 110.3444, "ranking": 101},
    {"name": "海南医学院", "province": "海南", "city": "海口", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hainmc.edu.cn", "latitude": 20.0244, "longitude": 110.3544, "ranking": 180},
    # 民办院校
    {"name": "北京城市学院", "province": "北京", "city": "北京", "level": "民办", "type": "综合",
     "tags": [], "tuition_min": 25000, "tuition_max": 40000,
     "website": "https://www.bcu.edu.cn", "latitude": 40.0044, "longitude": 116.3144, "ranking": 250},
    {"name": "上海杉达学院", "province": "上海", "city": "上海", "level": "民办", "type": "综合",
     "tags": [], "tuition_min": 30000, "tuition_max": 45000,
     "website": "https://www.sandau.edu.cn", "latitude": 31.2344, "longitude": 121.5444, "ranking": 260},
    {"name": "浙江树人学院", "province": "浙江", "city": "杭州", "level": "民办", "type": "综合",
     "tags": [], "tuition_min": 28000, "tuition_max": 40000,
     "website": "https://www.zjsru.edu.cn", "latitude": 30.3344, "longitude": 120.1644, "ranking": 265},
    {"name": "广东白云学院", "province": "广东", "city": "广州", "level": "民办", "type": "理工",
     "tags": [], "tuition_min": 28000, "tuition_max": 40000,
     "website": "https://www.baiyunu.edu.cn", "latitude": 23.2244, "longitude": 113.3344, "ranking": 270},
    {"name": "武昌理工学院", "province": "湖北", "city": "武汉", "level": "民办", "type": "理工",
     "tags": [], "tuition_min": 22000, "tuition_max": 35000,
     "website": "https://www.wut.edu.cn", "latitude": 30.4444, "longitude": 114.3844, "ranking": 275},
    {"name": "四川传媒学院", "province": "四川", "city": "成都", "level": "民办", "type": "艺术",
     "tags": [], "tuition_min": 18000, "tuition_max": 30000,
     "website": "https://www.scmc.edu.cn", "latitude": 30.7344, "longitude": 104.0444, "ranking": 280},
    {"name": "大连东软信息学院", "province": "辽宁", "city": "大连", "level": "民办", "type": "理工",
     "tags": [], "tuition_min": 25000, "tuition_max": 35000,
     "website": "https://www.dlu.edu.cn", "latitude": 38.8844, "longitude": 121.5544, "ranking": 285},
    {"name": "黄河科技学院", "province": "河南", "city": "郑州", "level": "民办", "type": "综合",
     "tags": [], "tuition_min": 18000, "tuition_max": 28000,
     "website": "https://www.hhstu.edu.cn", "latitude": 34.7244, "longitude": 113.6544, "ranking": 275},
    {"name": "西安培华学院", "province": "陕西", "city": "西安", "level": "民办", "type": "综合",
     "tags": [], "tuition_min": 20000, "tuition_max": 32000,
     "website": "https://www.peihua.edu.cn", "latitude": 34.2244, "longitude": 108.9544, "ranking": 280},
    {"name": "吉林外国语大学", "province": "吉林", "city": "长春", "level": "民办", "type": "语言",
     "tags": [], "tuition_min": 25000, "tuition_max": 35000,
     "website": "https://www.jisu.edu.cn", "latitude": 43.8244, "longitude": 125.3244, "ranking": 260},
    # 独立学院/应用技术大学
    {"name": "深圳技术大学", "province": "广东", "city": "深圳", "level": "普通本科", "type": "理工",
     "tags": ["应用技术"], "tuition_min": 6000, "tuition_max": 10000,
     "website": "https://www.sztu.edu.cn", "latitude": 22.6944, "longitude": 114.3544, "ranking": 145},
    {"name": "上海健康医学院", "province": "上海", "city": "上海", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.sumhs.edu.cn", "latitude": 31.1644, "longitude": 121.5944, "ranking": 170},
]


async def seed():
    async with async_session() as session:
        # 清空已有数据
        result = await session.execute(delete(University))
        print(f"Deleted {result.rowcount} existing universities")

        for data in UNIVERSITIES:
            uni = University(id=uuid.uuid4(), **data)
            session.add(uni)
        await session.commit()
        print(f"Inserted {len(UNIVERSITIES)} universities")


if __name__ == "__main__":
    asyncio.run(seed())