"""种子数据：985/211/双一流院校基础信息"""
import asyncio
import uuid
import sys
sys.path.insert(0, "backend")

from sqlalchemy.ext.asyncio import AsyncSession
from app.database import async_session
from app.models.university import University

UNIVERSITIES = [
    # ── 985 院校（39所） ──────────────────────────────────────────────
    # 北京
    {"name": "清华大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5000, "tuition_max": 10000,
     "website": "https://www.tsinghua.edu.cn", "latitude": 39.9994, "longitude": 116.3267},
    {"name": "北京大学", "province": "北京", "city": "北京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.pku.edu.cn", "latitude": 39.9870, "longitude": 116.3052},
    {"name": "中国人民大学", "province": "北京", "city": "北京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ruc.edu.cn", "latitude": 39.9685, "longitude": 116.3196},
    {"name": "北京航空航天大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.buaa.edu.cn", "latitude": 39.9831, "longitude": 116.3474},
    {"name": "北京理工大学", "province": "北京", "city": "北京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bit.edu.cn", "latitude": 39.9608, "longitude": 116.3164},
    {"name": "北京师范大学", "province": "北京", "city": "北京", "level": "985", "type": "师范",
     "tags": ["985", "211", "双一流"], "tuition_min": 4800, "tuition_max": 8000,
     "website": "https://www.bnu.edu.cn", "latitude": 39.9621, "longitude": 116.3575},
    {"name": "中国农业大学", "province": "北京", "city": "北京", "level": "985", "type": "农林",
     "tags": ["985", "211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.cau.edu.cn", "latitude": 40.0081, "longitude": 116.3543},
    {"name": "中央民族大学", "province": "北京", "city": "北京", "level": "985", "type": "民族",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.muc.edu.cn", "latitude": 39.9487, "longitude": 116.3328},
    # 上海
    {"name": "复旦大学", "province": "上海", "city": "上海", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5500, "tuition_max": 8500,
     "website": "https://www.fudan.edu.cn", "latitude": 31.2986, "longitude": 121.5034},
    {"name": "上海交通大学", "province": "上海", "city": "上海", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.sjtu.edu.cn", "latitude": 31.0282, "longitude": 121.4436},
    {"name": "同济大学", "province": "上海", "city": "上海", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.tongji.edu.cn", "latitude": 31.2837, "longitude": 121.5019},
    {"name": "华东师范大学", "province": "上海", "city": "上海", "level": "985", "type": "师范",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ecnu.edu.cn", "latitude": 31.2287, "longitude": 121.4063},
    # 天津
    {"name": "南开大学", "province": "天津", "city": "天津", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nankai.edu.cn", "latitude": 39.1152, "longitude": 117.1753},
    {"name": "天津大学", "province": "天津", "city": "天津", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.tju.edu.cn", "latitude": 39.1282, "longitude": 117.1858},
    # 辽宁
    {"name": "大连理工大学", "province": "辽宁", "city": "大连", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.dlut.edu.cn", "latitude": 38.8842, "longitude": 121.5297},
    {"name": "东北大学", "province": "辽宁", "city": "沈阳", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.neu.edu.cn", "latitude": 41.7698, "longitude": 123.4157},
    # 吉林
    {"name": "吉林大学", "province": "吉林", "city": "长春", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.jlu.edu.cn", "latitude": 43.8292, "longitude": 125.2743},
    # 黑龙江
    {"name": "哈尔滨工业大学", "province": "黑龙江", "city": "哈尔滨", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hit.edu.cn", "latitude": 45.7411, "longitude": 126.6278},
    # 江苏
    {"name": "南京大学", "province": "江苏", "city": "南京", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5200, "tuition_max": 7800,
     "website": "https://www.nju.edu.cn", "latitude": 32.0579, "longitude": 118.7781},
    {"name": "东南大学", "province": "江苏", "city": "南京", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.seu.edu.cn", "latitude": 32.0574, "longitude": 118.7899},
    # 浙江
    {"name": "浙江大学", "province": "浙江", "city": "杭州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.zju.edu.cn", "latitude": 30.3085, "longitude": 120.0864},
    # 安徽
    {"name": "中国科学技术大学", "province": "安徽", "city": "合肥", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4800, "tuition_max": 7000,
     "website": "https://www.ustc.edu.cn", "latitude": 31.8427, "longitude": 117.2654},
    # 福建
    {"name": "厦门大学", "province": "福建", "city": "厦门", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xmu.edu.cn", "latitude": 24.4365, "longitude": 118.0954},
    # 山东
    {"name": "山东大学", "province": "山东", "city": "济南", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdu.edu.cn", "latitude": 36.6687, "longitude": 116.9756},
    {"name": "中国海洋大学", "province": "山东", "city": "青岛", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7000,
     "website": "https://www.ouc.edu.cn", "latitude": 36.0671, "longitude": 120.3826},
    # 湖北
    {"name": "武汉大学", "province": "湖北", "city": "武汉", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.whu.edu.cn", "latitude": 30.5378, "longitude": 114.3626},
    {"name": "华中科技大学", "province": "湖北", "city": "武汉", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hust.edu.cn", "latitude": 30.5115, "longitude": 114.4143},
    # 湖南
    {"name": "湖南大学", "province": "湖南", "city": "长沙", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hnu.edu.cn", "latitude": 28.1834, "longitude": 112.9465},
    {"name": "中南大学", "province": "湖南", "city": "长沙", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.csu.edu.cn", "latitude": 28.1633, "longitude": 112.9332},
    {"name": "国防科技大学", "province": "湖南", "city": "长沙", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 0, "tuition_max": 0,
     "website": "https://www.nudt.edu.cn", "latitude": 28.2362, "longitude": 112.9834},
    # 广东
    {"name": "中山大学", "province": "广东", "city": "广州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 5160, "tuition_max": 8000,
     "website": "https://www.sysu.edu.cn", "latitude": 23.0934, "longitude": 113.2971},
    {"name": "华南理工大学", "province": "广东", "city": "广州", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.scut.edu.cn", "latitude": 23.1554, "longitude": 113.3518},
    # 重庆
    {"name": "重庆大学", "province": "重庆", "city": "重庆", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqu.edu.cn", "latitude": 29.5638, "longitude": 106.4689},
    # 四川
    {"name": "四川大学", "province": "四川", "city": "成都", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4440, "tuition_max": 7500,
     "website": "https://www.scu.edu.cn", "latitude": 30.6301, "longitude": 104.0826},
    {"name": "电子科技大学", "province": "四川", "city": "成都", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4900, "tuition_max": 8000,
     "website": "https://www.uestc.edu.cn", "latitude": 30.7592, "longitude": 103.9356},
    # 陕西
    {"name": "西安交通大学", "province": "陕西", "city": "西安", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流", "C9"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.xjtu.edu.cn", "latitude": 34.2358, "longitude": 108.9872},
    {"name": "西北工业大学", "province": "陕西", "city": "西安", "level": "985", "type": "理工",
     "tags": ["985", "211", "双一流"], "tuition_min": 4500, "tuition_max": 7500,
     "website": "https://www.nwpu.edu.cn", "latitude": 34.2442, "longitude": 108.9103},
    {"name": "西北农林科技大学", "province": "陕西", "city": "杨凌", "level": "985", "type": "农林",
     "tags": ["985", "211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nwafu.edu.cn", "latitude": 34.2682, "longitude": 108.0742},
    # 甘肃
    {"name": "兰州大学", "province": "甘肃", "city": "兰州", "level": "985", "type": "综合",
     "tags": ["985", "211", "双一流"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.lzu.edu.cn", "latitude": 36.0514, "longitude": 103.8514},

    # ── 纯211院校（非985） ──────────────────────────────────────────
    # 北京
    {"name": "北京交通大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bjtu.edu.cn", "latitude": 39.9578, "longitude": 116.3478},
    {"name": "北京科技大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ustb.edu.cn", "latitude": 39.9853, "longitude": 116.3572},
    {"name": "北京化工大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.buct.edu.cn", "latitude": 40.0088, "longitude": 116.3977},
    {"name": "北京邮电大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bupt.edu.cn", "latitude": 39.9633, "longitude": 116.3567},
    {"name": "北京林业大学", "province": "北京", "city": "北京", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.bjfu.edu.cn", "latitude": 40.0088, "longitude": 116.3477},
    {"name": "北京中医药大学", "province": "北京", "city": "北京", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.bucm.edu.cn", "latitude": 39.9714, "longitude": 116.4075},
    {"name": "中国传媒大学", "province": "北京", "city": "北京", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cuc.edu.cn", "latitude": 39.9357, "longitude": 116.3953},
    {"name": "中央财经大学", "province": "北京", "city": "北京", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cufe.edu.cn", "latitude": 39.9572, "longitude": 116.3493},
    {"name": "对外经济贸易大学", "province": "北京", "city": "北京", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.uibe.edu.cn", "latitude": 39.9904, "longitude": 116.3922},
    {"name": "北京外国语大学", "province": "北京", "city": "北京", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bfsu.edu.cn", "latitude": 39.9622, "longitude": 116.3184},
    {"name": "中国政法大学", "province": "北京", "city": "北京", "level": "211", "type": "政法",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cupl.edu.cn", "latitude": 40.0096, "longitude": 116.3539},
    {"name": "华北电力大学", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ncepu.edu.cn", "latitude": 40.0577, "longitude": 116.2386},
    {"name": "中国矿业大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cumtb.edu.cn", "latitude": 39.9538, "longitude": 116.3568},
    {"name": "中国地质大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cugb.edu.cn", "latitude": 39.9719, "longitude": 116.3365},
    {"name": "中国石油大学(北京)", "province": "北京", "city": "北京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cup.edu.cn", "latitude": 40.0678, "longitude": 116.2665},
    {"name": "北京体育大学", "province": "北京", "city": "北京", "level": "211", "type": "体育",
     "tags": ["211"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bsu.edu.cn", "latitude": 40.0652, "longitude": 116.3283},
    # 上海
    {"name": "上海财经大学", "province": "上海", "city": "上海", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shufe.edu.cn", "latitude": 31.2239, "longitude": 121.4722},
    {"name": "上海外国语大学", "province": "上海", "city": "上海", "level": "211", "type": "语言",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shisu.edu.cn", "latitude": 31.2056, "longitude": 121.4503},
    {"name": "上海大学", "province": "上海", "city": "上海", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shu.edu.cn", "latitude": 31.3174, "longitude": 121.4028},
    {"name": "东华大学", "province": "上海", "city": "上海", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dhu.edu.cn", "latitude": 31.2294, "longitude": 121.4627},
    {"name": "华东理工大学", "province": "上海", "city": "上海", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ecust.edu.cn", "latitude": 31.1474, "longitude": 121.4033},
    # 天津
    {"name": "天津医科大学", "province": "天津", "city": "天津", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.tmu.edu.cn", "latitude": 39.1207, "longitude": 117.2015},
    # 河北
    {"name": "河北工业大学", "province": "河北", "city": "天津", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hebut.edu.cn", "latitude": 39.1502, "longitude": 117.1823},
    # 山西
    {"name": "太原理工大学", "province": "山西", "city": "太原", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tyut.edu.cn", "latitude": 37.8498, "longitude": 112.5562},
    # 内蒙古
    {"name": "内蒙古大学", "province": "内蒙古", "city": "呼和浩特", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.imu.edu.cn", "latitude": 40.8142, "longitude": 111.7476},
    # 辽宁
    {"name": "辽宁大学", "province": "辽宁", "city": "沈阳", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lnu.edu.cn", "latitude": 41.7228, "longitude": 123.4248},
    # 吉林
    {"name": "延边大学", "province": "吉林", "city": "延吉", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.ybu.edu.cn", "latitude": 42.8914, "longitude": 129.4842},
    # 黑龙江
    {"name": "哈尔滨工程大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hrbeu.edu.cn", "latitude": 45.7464, "longitude": 126.6186},
    {"name": "东北农业大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.neau.edu.cn", "latitude": 45.7434, "longitude": 126.7034},
    {"name": "东北林业大学", "province": "黑龙江", "city": "哈尔滨", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nefu.edu.cn", "latitude": 45.7544, "longitude": 126.6403},
    # 江苏
    {"name": "苏州大学", "province": "江苏", "city": "苏州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.suda.edu.cn", "latitude": 31.3034, "longitude": 120.6403},
    {"name": "南京航空航天大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nuaa.edu.cn", "latitude": 32.0423, "longitude": 118.7984},
    {"name": "南京理工大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njust.edu.cn", "latitude": 32.0608, "longitude": 118.8344},
    {"name": "中国矿业大学", "province": "江苏", "city": "徐州", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cumt.edu.cn", "latitude": 34.2235, "longitude": 117.1442},
    {"name": "河海大学", "province": "江苏", "city": "南京", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.hhu.edu.cn", "latitude": 32.0614, "longitude": 118.7743},
    {"name": "南京农业大学", "province": "江苏", "city": "南京", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 6000,
     "website": "https://www.njau.edu.cn", "latitude": 32.0425, "longitude": 118.8543},
    {"name": "南京师范大学", "province": "江苏", "city": "南京", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.nnu.edu.cn", "latitude": 32.1027, "longitude": 118.8775},
    {"name": "江南大学", "province": "江苏", "city": "无锡", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jiangnan.edu.cn", "latitude": 31.0534, "longitude": 120.2603},
    {"name": "中国药科大学", "province": "江苏", "city": "南京", "level": "211", "type": "医药",
     "tags": ["211", "双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cpu.edu.cn", "latitude": 32.0472, "longitude": 118.8654},
    # 浙江
    # (浙江大学已在985中)
    # 安徽
    {"name": "安徽大学", "province": "安徽", "city": "合肥", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahu.edu.cn", "latitude": 31.7847, "longitude": 117.2784},
    # 福建
    {"name": "福州大学", "province": "福建", "city": "福州", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fzu.edu.cn", "latitude": 26.0674, "longitude": 119.1878},
    # 江西
    {"name": "南昌大学", "province": "江西", "city": "南昌", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ncu.edu.cn", "latitude": 28.6774, "longitude": 115.8662},
    # 山东
    {"name": "中国石油大学(华东)", "province": "山东", "city": "青岛", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.upc.edu.cn", "latitude": 36.0094, "longitude": 120.0964},
    # 河南
    {"name": "郑州大学", "province": "河南", "city": "郑州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.zzu.edu.cn", "latitude": 34.7578, "longitude": 113.6634},
    # 湖北
    {"name": "武汉理工大学", "province": "湖北", "city": "武汉", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.whut.edu.cn", "latitude": 30.5154, "longitude": 114.4234},
    {"name": "中南财经政法大学", "province": "湖北", "city": "武汉", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zuel.edu.cn", "latitude": 30.4784, "longitude": 114.3614},
    {"name": "华中师范大学", "province": "湖北", "city": "武汉", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ccnu.edu.cn", "latitude": 30.4984, "longitude": 114.3644},
    {"name": "华中农业大学", "province": "湖北", "city": "武汉", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.hzau.edu.cn", "latitude": 30.4714, "longitude": 114.3654},
    {"name": "中国地质大学(武汉)", "province": "湖北", "city": "武汉", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cug.edu.cn", "latitude": 30.5214, "longitude": 114.4014},
    # 湖南
    {"name": "湖南师范大学", "province": "湖南", "city": "长沙", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.hunnu.edu.cn", "latitude": 28.1834, "longitude": 112.9395},
    # 广东
    {"name": "暨南大学", "province": "广东", "city": "广州", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jnu.edu.cn", "latitude": 23.1254, "longitude": 113.3418},
    {"name": "华南师范大学", "province": "广东", "city": "广州", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.scnu.edu.cn", "latitude": 23.1558, "longitude": 113.3488},
    # 广西
    {"name": "广西大学", "province": "广西", "city": "南宁", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.gxu.edu.cn", "latitude": 22.8254, "longitude": 108.3178},
    # 海南
    {"name": "海南大学", "province": "海南", "city": "海口", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hainu.edu.cn", "latitude": 20.0444, "longitude": 110.3494},
    # 重庆
    {"name": "西南大学", "province": "重庆", "city": "重庆", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swu.edu.cn", "latitude": 29.5574, "longitude": 106.4684},
    # 四川
    {"name": "西南财经大学", "province": "四川", "city": "成都", "level": "211", "type": "财经",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.swufe.edu.cn", "latitude": 30.6901, "longitude": 104.0626},
    {"name": "四川农业大学", "province": "四川", "city": "雅安", "level": "211", "type": "农林",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.sicau.edu.cn", "latitude": 29.9734, "longitude": 103.0034},
    # 贵州
    {"name": "贵州大学", "province": "贵州", "city": "贵阳", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gzu.edu.cn", "latitude": 26.4274, "longitude": 106.6714},
    # 云南
    {"name": "云南大学", "province": "云南", "city": "昆明", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynu.edu.cn", "latitude": 25.0424, "longitude": 102.8374},
    # 西藏
    {"name": "西藏大学", "province": "西藏", "city": "拉萨", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3000, "tuition_max": 5000,
     "website": "https://www.utibet.edu.cn", "latitude": 29.6514, "longitude": 91.1014},
    # 陕西
    {"name": "西北大学", "province": "陕西", "city": "西安", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nwu.edu.cn", "latitude": 34.2654, "longitude": 108.9054},
    {"name": "西安电子科技大学", "province": "陕西", "city": "西安", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.xidian.edu.cn", "latitude": 34.2454, "longitude": 108.9144},
    {"name": "陕西师范大学", "province": "陕西", "city": "西安", "level": "211", "type": "师范",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.snnu.edu.cn", "latitude": 34.1644, "longitude": 108.9614},
    {"name": "长安大学", "province": "陕西", "city": "西安", "level": "211", "type": "理工",
     "tags": ["211", "双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.chd.edu.cn", "latitude": 34.2374, "longitude": 108.9414},
    # 甘肃
    # (兰州大学已在985中)
    # 青海
    # 宁夏
    {"name": "宁夏大学", "province": "宁夏", "city": "银川", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.nxu.edu.cn", "latitude": 38.4874, "longitude": 106.0774},
    # 新疆
    {"name": "新疆大学", "province": "新疆", "city": "乌鲁木齐", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.xju.edu.cn", "latitude": 43.7874, "longitude": 87.5974},
    {"name": "石河子大学", "province": "新疆", "city": "石河子", "level": "211", "type": "综合",
     "tags": ["211", "双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.shzu.edu.cn", "latitude": 44.3074, "longitude": 86.0774},

    # ── 纯双一流院校（非985/非211） ─────────────────────────────────
    # 北京
    {"name": "中国科学院大学", "province": "北京", "city": "北京", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ucas.edu.cn", "latitude": 39.9834, "longitude": 116.3534},
    {"name": "首都师范大学", "province": "北京", "city": "北京", "level": "双一流", "type": "师范",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cnu.edu.cn", "latitude": 39.9684, "longitude": 116.2984},
    {"name": "外交学院", "province": "北京", "city": "北京", "level": "双一流", "type": "政法",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cfau.edu.cn", "latitude": 39.9374, "longitude": 116.3254},
    {"name": "中国人民公安大学", "province": "北京", "city": "北京", "level": "双一流", "type": "政法",
     "tags": ["双一流"], "tuition_min": 0, "tuition_max": 0,
     "website": "https://www.ppsuc.edu.cn", "latitude": 39.9414, "longitude": 116.3284},
    {"name": "中央音乐学院", "province": "北京", "city": "北京", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.ccom.edu.cn", "latitude": 39.9374, "longitude": 116.3534},
    # 上海
    {"name": "上海科技大学", "province": "上海", "city": "上海", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shanghaitech.edu.cn", "latitude": 31.0754, "longitude": 121.8324},
    {"name": "上海体育学院", "province": "上海", "city": "上海", "level": "双一流", "type": "体育",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shsus.edu.cn", "latitude": 31.2984, "longitude": 121.4744},
    {"name": "上海音乐学院", "province": "上海", "city": "上海", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.shcmusic.edu.cn", "latitude": 31.2144, "longitude": 121.4624},
    # 天津
    {"name": "天津工业大学", "province": "天津", "city": "天津", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tiangong.edu.cn", "latitude": 39.1304, "longitude": 117.1724},
    # 浙江
    {"name": "宁波大学", "province": "浙江", "city": "宁波", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.nbu.edu.cn", "latitude": 29.8744, "longitude": 121.5634},
    {"name": "中国美术学院", "province": "浙江", "city": "杭州", "level": "双一流", "type": "艺术",
     "tags": ["双一流"], "tuition_min": 8000, "tuition_max": 15000,
     "website": "https://www.caa.edu.cn", "latitude": 30.1744, "longitude": 120.0624},
    # 江苏
    {"name": "南京邮电大学", "province": "江苏", "city": "南京", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njupt.edu.cn", "latitude": 32.0744, "longitude": 118.7744},
    {"name": "南京信息工程大学", "province": "江苏", "city": "南京", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.nuist.edu.cn", "latitude": 32.1874, "longitude": 118.7124},
    # 江西
    {"name": "江西财经大学", "province": "江西", "city": "南昌", "level": "双一流", "type": "财经",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jxufe.edu.cn", "latitude": 28.7144, "longitude": 115.8744},
    # 河南
    {"name": "河南大学", "province": "河南", "city": "开封", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.henu.edu.cn", "latitude": 34.7844, "longitude": 114.3524},
    # 湖南
    {"name": "湘潭大学", "province": "湖南", "city": "湘潭", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xtu.edu.cn", "latitude": 27.8744, "longitude": 112.9374},
    # 广东
    {"name": "南方科技大学", "province": "广东", "city": "深圳", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sustech.edu.cn", "latitude": 22.5944, "longitude": 113.9744},
    {"name": "深圳大学", "province": "广东", "city": "深圳", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.szu.edu.cn", "latitude": 22.5344, "longitude": 113.9374},
    {"name": "华南农业大学", "province": "广东", "city": "广州", "level": "双一流", "type": "农林",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.scau.edu.cn", "latitude": 23.1644, "longitude": 113.3544},
    {"name": "广州医科大学", "province": "广东", "city": "广州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gzhmu.edu.cn", "latitude": 23.1244, "longitude": 113.2644},
    {"name": "广州中医药大学", "province": "广东", "city": "广州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gzucm.edu.cn", "latitude": 23.0744, "longitude": 113.3344},
    # 四川
    {"name": "成都理工大学", "province": "四川", "city": "成都", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cdut.edu.cn", "latitude": 30.6744, "longitude": 104.1344},
    {"name": "西南石油大学", "province": "四川", "city": "成都", "level": "双一流", "type": "理工",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swpu.edu.cn", "latitude": 30.7144, "longitude": 104.1544},
    {"name": "成都中医药大学", "province": "四川", "city": "成都", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cdutcm.edu.cn", "latitude": 30.6844, "longitude": 104.0644},
    {"name": "西南医科大学", "province": "四川", "city": "泸州", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.swmu.edu.cn", "latitude": 28.8944, "longitude": 105.4344},
    # 重庆
    {"name": "重庆医科大学", "province": "重庆", "city": "重庆", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.cqmu.edu.cn", "latitude": 29.5644, "longitude": 106.4744},
    # 黑龙江
    {"name": "哈尔滨医科大学", "province": "黑龙江", "city": "哈尔滨", "level": "双一流", "type": "医药",
     "tags": ["双一流"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hmu.edu.cn", "latitude": 45.7344, "longitude": 126.6244},
    # 山西
    {"name": "山西大学", "province": "山西", "city": "太原", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sxu.edu.cn", "latitude": 37.7944, "longitude": 112.5744},
    # 青海
    {"name": "青海大学", "province": "青海", "city": "西宁", "level": "双一流", "type": "综合",
     "tags": ["双一流"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.qhu.edu.cn", "latitude": 36.6144, "longitude": 101.7544},

    # ── 普通本科院校（省属重点/知名公办） ───────────────────────────
    # 北京
    {"name": "首都经济贸易大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cueb.edu.cn", "latitude": 39.8644, "longitude": 116.3544},
    {"name": "北京工商大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.btbu.edu.cn", "latitude": 39.8944, "longitude": 116.3144},
    {"name": "北京建筑大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bucea.edu.cn", "latitude": 39.9244, "longitude": 116.2844},
    {"name": "北京第二外国语学院", "province": "北京", "city": "北京", "level": "普通本科", "type": "语言",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.bisu.edu.cn", "latitude": 39.9144, "longitude": 116.5544},
    {"name": "北方工业大学", "province": "北京", "city": "北京", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ncut.edu.cn", "latitude": 39.9344, "longitude": 116.2244},
    # 上海
    {"name": "上海理工大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.usst.edu.cn", "latitude": 31.2744, "longitude": 121.4744},
    {"name": "上海师范大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shnu.edu.cn", "latitude": 31.1744, "longitude": 121.4144},
    {"name": "上海海事大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.shmtu.edu.cn", "latitude": 31.0644, "longitude": 121.8344},
    {"name": "上海对外经贸大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "财经",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.suibe.edu.cn", "latitude": 31.2344, "longitude": 121.4244},
    {"name": "上海工程技术大学", "province": "上海", "city": "上海", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.sues.edu.cn", "latitude": 31.2644, "longitude": 121.2144},
    # 天津
    {"name": "天津师范大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tjnu.edu.cn", "latitude": 39.0844, "longitude": 117.1644},
    {"name": "天津科技大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tust.edu.cn", "latitude": 39.1144, "longitude": 117.2144},
    {"name": "天津理工大学", "province": "天津", "city": "天津", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.tjut.edu.cn", "latitude": 39.1044, "longitude": 117.1744},
    # 河北
    {"name": "河北大学", "province": "河北", "city": "保定", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hbu.edu.cn", "latitude": 38.7644, "longitude": 115.2744},
    {"name": "燕山大学", "province": "河北", "city": "秦皇岛", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ysu.edu.cn", "latitude": 39.9644, "longitude": 119.5244},
    {"name": "河北师范大学", "province": "河北", "city": "石家庄", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hebtu.edu.cn", "latitude": 38.0744, "longitude": 114.4744},
    {"name": "河北医科大学", "province": "河北", "city": "石家庄", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.hebmu.edu.cn", "latitude": 38.0344, "longitude": 114.4844},
    # 山西
    {"name": "中北大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nuc.edu.cn", "latitude": 37.8444, "longitude": 112.5144},
    {"name": "山西医科大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.sxmu.edu.cn", "latitude": 37.8644, "longitude": 112.5744},
    {"name": "山西师范大学", "province": "山西", "city": "太原", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sxnu.edu.cn", "latitude": 37.8144, "longitude": 112.5344},
    # 内蒙古
    {"name": "内蒙古师范大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.imnu.edu.cn", "latitude": 40.8344, "longitude": 111.7544},
    {"name": "内蒙古医科大学", "province": "内蒙古", "city": "呼和浩特", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.immu.edu.cn", "latitude": 40.7944, "longitude": 111.7244},
    # 辽宁
    {"name": "辽宁师范大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lnnu.edu.cn", "latitude": 38.8744, "longitude": 121.5144},
    {"name": "沈阳工业大学", "province": "辽宁", "city": "沈阳", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sut.edu.cn", "latitude": 41.7744, "longitude": 123.3744},
    {"name": "大连大学", "province": "辽宁", "city": "大连", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.dlu.edu.cn", "latitude": 38.8944, "longitude": 121.6844},
    # 吉林
    {"name": "长春理工大学", "province": "吉林", "city": "长春", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cust.edu.cn", "latitude": 43.8544, "longitude": 125.2944},
    {"name": "东北电力大学", "province": "吉林", "city": "吉林", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nepu.edu.cn", "latitude": 43.8344, "longitude": 126.5244},
    {"name": "吉林师范大学", "province": "吉林", "city": "四平", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.jlnu.edu.cn", "latitude": 43.1744, "longitude": 124.3744},
    # 黑龙江
    {"name": "黑龙江大学", "province": "黑龙江", "city": "哈尔滨", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 8000,
     "website": "https://www.hljtu.edu.cn", "latitude": 45.7344, "longitude": 126.6144},
    {"name": "齐齐哈尔大学", "province": "黑龙江", "city": "齐齐哈尔", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.qqhru.edu.cn", "latitude": 47.3544, "longitude": 123.9544},
    # 江苏
    {"name": "扬州大学", "province": "江苏", "city": "扬州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.yzu.edu.cn", "latitude": 32.3944, "longitude": 119.4244},
    {"name": "江苏大学", "province": "江苏", "city": "镇江", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.ujs.edu.cn", "latitude": 32.2044, "longitude": 119.4544},
    {"name": "南京工业大学", "province": "江苏", "city": "南京", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5200, "tuition_max": 8000,
     "website": "https://www.njtech.edu.cn", "latitude": 32.0644, "longitude": 118.7844},
    {"name": "江苏师范大学", "province": "江苏", "city": "徐州", "level": "普通本科", "type": "师范",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.jsnu.edu.cn", "latitude": 34.2244, "longitude": 117.1844},
    {"name": "常州大学", "province": "江苏", "city": "常州", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.cczu.edu.cn", "latitude": 31.7544, "longitude": 119.9244},
    # 浙江
    {"name": "浙江工业大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjut.edu.cn", "latitude": 30.2144, "longitude": 120.0644},
    {"name": "浙江师范大学", "province": "浙江", "city": "金华", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjnu.edu.cn", "latitude": 29.0144, "longitude": 119.6344},
    {"name": "浙江理工大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zstu.edu.cn", "latitude": 30.1744, "longitude": 120.2144},
    {"name": "浙江工商大学", "province": "浙江", "city": "杭州", "level": "普通本科", "type": "财经",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.zjgsu.edu.cn", "latitude": 30.2644, "longitude": 120.1544},
    {"name": "温州大学", "province": "浙江", "city": "温州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.wzu.edu.cn", "latitude": 28.0144, "longitude": 120.6344},
    # 安徽
    {"name": "安徽师范大学", "province": "安徽", "city": "芜湖", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahnu.edu.cn", "latitude": 31.3344, "longitude": 118.3844},
    {"name": "安徽工业大学", "province": "安徽", "city": "马鞍山", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ahut.edu.cn", "latitude": 31.6744, "longitude": 118.5144},
    {"name": "安徽理工大学", "province": "安徽", "city": "淮南", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.aust.edu.cn", "latitude": 32.6344, "longitude": 116.9744},
    {"name": "安徽医科大学", "province": "安徽", "city": "合肥", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.ahmu.edu.cn", "latitude": 31.8144, "longitude": 117.2744},
    # 福建
    {"name": "福建师范大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fjnu.edu.cn", "latitude": 26.0744, "longitude": 119.2944},
    {"name": "华侨大学", "province": "福建", "city": "泉州", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hqu.edu.cn", "latitude": 24.8744, "longitude": 118.6744},
    {"name": "福建医科大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.fjmu.edu.cn", "latitude": 26.0444, "longitude": 119.2644},
    {"name": "福建农林大学", "province": "福建", "city": "福州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.fafu.edu.cn", "latitude": 26.0344, "longitude": 119.2344},
    # 江西
    {"name": "江西师范大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.jxnu.edu.cn", "latitude": 28.6844, "longitude": 115.8544},
    {"name": "南昌航空大学", "province": "江西", "city": "南昌", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.nchu.edu.cn", "latitude": 28.6944, "longitude": 115.8744},
    # 山东
    {"name": "山东师范大学", "province": "山东", "city": "济南", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdnu.edu.cn", "latitude": 36.6544, "longitude": 116.9544},
    {"name": "青岛大学", "province": "山东", "city": "青岛", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.qdu.edu.cn", "latitude": 36.0744, "longitude": 120.3744},
    {"name": "济南大学", "province": "山东", "city": "济南", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ujn.edu.cn", "latitude": 36.6744, "longitude": 116.9644},
    {"name": "山东科技大学", "province": "山东", "city": "青岛", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdust.edu.cn", "latitude": 36.0044, "longitude": 120.1144},
    {"name": "山东农业大学", "province": "山东", "city": "泰安", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sdau.edu.cn", "latitude": 36.1644, "longitude": 117.1544},
    # 河南
    {"name": "河南师范大学", "province": "河南", "city": "新乡", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.htu.edu.cn", "latitude": 35.3044, "longitude": 113.9244},
    {"name": "河南科技大学", "province": "河南", "city": "洛阳", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.haust.edu.cn", "latitude": 34.6244, "longitude": 112.4244},
    {"name": "河南理工大学", "province": "河南", "city": "焦作", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hpu.edu.cn", "latitude": 35.2244, "longitude": 113.2444},
    {"name": "河南农业大学", "province": "河南", "city": "郑州", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.henau.edu.cn", "latitude": 34.7644, "longitude": 113.6544},
    # 湖北
    {"name": "湖北大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hubu.edu.cn", "latitude": 30.5644, "longitude": 114.3844},
    {"name": "武汉科技大学", "province": "湖北", "city": "武汉", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.wust.edu.cn", "latitude": 30.4344, "longitude": 114.3944},
    {"name": "三峡大学", "province": "湖北", "city": "宜昌", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ctgu.edu.cn", "latitude": 30.7244, "longitude": 111.3044},
    {"name": "长江大学", "province": "湖北", "city": "荆州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.yangtzeu.edu.cn", "latitude": 30.3444, "longitude": 112.2044},
    # 湖南
    {"name": "长沙理工大学", "province": "湖南", "city": "长沙", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.csust.edu.cn", "latitude": 28.1544, "longitude": 112.9344},
    {"name": "湖南科技大学", "province": "湖南", "city": "湘潭", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hnust.edu.cn", "latitude": 27.8944, "longitude": 112.9244},
    {"name": "湖南农业大学", "province": "湖南", "city": "长沙", "level": "普通本科", "type": "农林",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.hunau.edu.cn", "latitude": 28.1844, "longitude": 112.9544},
    # 广东
    {"name": "广东工业大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gdut.edu.cn", "latitude": 23.1444, "longitude": 113.3744},
    {"name": "广东外语外贸大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "语言",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gdufs.edu.cn", "latitude": 23.1044, "longitude": 113.2744},
    {"name": "广州大学", "province": "广东", "city": "广州", "level": "普通本科", "type": "综合",
     "tags": ["省属重点"], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.gzhu.edu.cn", "latitude": 23.0644, "longitude": 113.3544},
    {"name": "汕头大学", "province": "广东", "city": "汕头", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.stu.edu.cn", "latitude": 23.3544, "longitude": 116.6344},
    {"name": "东莞理工学院", "province": "广东", "city": "东莞", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 5000, "tuition_max": 8000,
     "website": "https://www.dgut.edu.cn", "latitude": 22.9544, "longitude": 113.8844},
    {"name": "广东医科大学", "province": "广东", "city": "湛江", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gdmu.edu.cn", "latitude": 21.2644, "longitude": 110.3144},
    # 广西
    {"name": "广西师范大学", "province": "广西", "city": "桂林", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.gxnu.edu.cn", "latitude": 25.2744, "longitude": 110.3144},
    {"name": "桂林电子科技大学", "province": "广西", "city": "桂林", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.guet.edu.cn", "latitude": 25.2644, "longitude": 110.3244},
    {"name": "广西医科大学", "province": "广西", "city": "南宁", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gxmu.edu.cn", "latitude": 22.8244, "longitude": 108.3244},
    # 海南
    {"name": "海南师范大学", "province": "海南", "city": "海口", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.hainnu.edu.cn", "latitude": 20.0144, "longitude": 110.3344},
    # 重庆
    {"name": "重庆邮电大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqupt.edu.cn", "latitude": 29.5244, "longitude": 106.4644},
    {"name": "重庆交通大学", "province": "重庆", "city": "重庆", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cqjtu.edu.cn", "latitude": 29.5744, "longitude": 106.4944},
    # 四川
    {"name": "四川师范大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sicnu.edu.cn", "latitude": 30.6544, "longitude": 104.0644},
    {"name": "成都信息工程大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cuit.edu.cn", "latitude": 30.5644, "longitude": 103.9844},
    {"name": "西南民族大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "民族",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.swun.edu.cn", "latitude": 30.5844, "longitude": 104.0444},
    {"name": "成都大学", "province": "四川", "city": "成都", "level": "普通本科", "type": "综合",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.cdu.edu.cn", "latitude": 30.6844, "longitude": 104.1744},
    # 贵州
    {"name": "贵州师范大学", "province": "贵州", "city": "贵阳", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gznu.edu.cn", "latitude": 26.5444, "longitude": 106.7144},
    {"name": "贵州医科大学", "province": "贵州", "city": "贵阳", "level": "普通本科", "type": "医药",
     "tags": [], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.gmu.edu.cn", "latitude": 26.4144, "longitude": 106.6644},
    # 云南
    {"name": "昆明理工大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.kust.edu.cn", "latitude": 25.0444, "longitude": 102.8244},
    {"name": "云南师范大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynnu.edu.cn", "latitude": 25.0144, "longitude": 102.7844},
    {"name": "云南农业大学", "province": "云南", "city": "昆明", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.ynau.edu.cn", "latitude": 25.0444, "longitude": 102.7344},
    # 陕西
    {"name": "西安建筑科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xauat.edu.cn", "latitude": 34.2444, "longitude": 108.9044},
    {"name": "西安理工大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xaut.edu.cn", "latitude": 34.2544, "longitude": 108.9544},
    {"name": "陕西科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.sust.edu.cn", "latitude": 34.2144, "longitude": 108.9444},
    {"name": "西安科技大学", "province": "陕西", "city": "西安", "level": "普通本科", "type": "理工",
     "tags": [], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.xust.edu.cn", "latitude": 34.2344, "longitude": 108.9244},
    # 甘肃
    {"name": "西北师范大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 4200, "tuition_max": 7000,
     "website": "https://www.nwnu.edu.cn", "latitude": 36.0744, "longitude": 103.8244},
    {"name": "兰州理工大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "理工",
     "tags": ["省属重点"], "tuition_min": 4500, "tuition_max": 8000,
     "website": "https://www.lut.edu.cn", "latitude": 36.0444, "longitude": 103.8044},
    {"name": "甘肃农业大学", "province": "甘肃", "city": "兰州", "level": "普通本科", "type": "农林",
     "tags": [], "tuition_min": 4000, "tuition_max": 7000,
     "website": "https://www.gsau.edu.cn", "latitude": 36.0544, "longitude": 103.8344},
    # 青海
    {"name": "青海师范大学", "province": "青海", "city": "西宁", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.qhnu.edu.cn", "latitude": 36.5944, "longitude": 101.7244},
    # 宁夏
    {"name": "宁夏医科大学", "province": "宁夏", "city": "银川", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.nxmu.edu.cn", "latitude": 38.4744, "longitude": 106.0744},
    # 新疆
    {"name": "新疆师范大学", "province": "新疆", "city": "乌鲁木齐", "level": "普通本科", "type": "师范",
     "tags": ["省属重点"], "tuition_min": 3500, "tuition_max": 6000,
     "website": "https://www.xjnnu.edu.cn", "latitude": 43.7944, "longitude": 87.5944},
    {"name": "新疆医科大学", "province": "新疆", "city": "乌鲁木齐", "level": "普通本科", "type": "医药",
     "tags": ["省属重点"], "tuition_min": 5500, "tuition_max": 9000,
     "website": "https://www.xjmu.edu.cn", "latitude": 43.7744, "longitude": 87.6144},
]


async def seed():
    async with async_session() as session:
        for data in UNIVERSITIES:
            uni = University(id=uuid.uuid4(), **data)
            session.add(uni)
        await session.commit()
        print(f"Inserted {len(UNIVERSITIES)} universities")


if __name__ == "__main__":
    asyncio.run(seed())